//! zod emitter: one runtime schema per input type. Reads only the IR.
//!
//! The schemas restate exactly what the Rust server enforces, because both are
//! generated from the same `@length` / `@range` / `@pattern` declarations. That
//! is the point of generating them rather than writing them: a client-side check
//! that can disagree with the server is worse than no check at all.
//!
//! Only inputs get a schema. An output is what the server sent, and re-checking
//! it in the browser would express doubt the type system already settled.

use std::collections::BTreeSet;
use std::fmt::Write;

use crate::ir::*;

const HEADER: &str = "// @generated by graphql-rpcgen. Source of truth: api/**/*.graphql
// DO NOT EDIT MANUALLY.
";

const PREAMBLE: &str = r#"
import { z } from 'zod'
"#;

/// Scalars spelled inline at every use site.
///
/// The GraphQL primitives carry no format and no constraints of their own, so a
/// named schema for them would only add a level of indirection to read through.
const PRIMITIVES: [&str; 5] = ["String", "Int", "Float", "Boolean", "ID"];

pub fn generate(api: &Api) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(PREAMBLE);

    emit_scalars(&mut out, api);
    emit_enums(&mut out, api);
    emit_inputs(&mut out, api);
    emit_registry(&mut out, api);

    out
}

fn emit_doc(out: &mut String, indent: &str, description: &Option<String>) {
    let Some(text) = description else { return };
    if text.lines().count() == 1 {
        let _ = writeln!(out, "{indent}/** {text} */");
        return;
    }
    let _ = writeln!(out, "{indent}/**");
    for line in text.lines() {
        let _ = writeln!(out, "{indent} * {line}");
    }
    let _ = writeln!(out, "{indent} */");
}

fn schema_name(type_name: &str) -> String {
    format!("{type_name}Schema")
}

/// A TypeScript string literal holding `value`.
///
/// The same quoting `generate_typescript` applies, and for the same reason: an
/// enum's wire spelling is whatever the other end calls it, apostrophe
/// included. The two emitters have to agree, since a `z.enum` member and the
/// literal type it validates are the same string.
fn quoted(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r");
    format!("'{escaped}'")
}

/// A named schema per domain scalar, so a rule the scalar declares is written
/// once and every field of that type inherits it.
fn emit_scalars(out: &mut String, api: &Api) {
    for ty in &api.types {
        let ApiType::Scalar(s) = ty else { continue };
        if PRIMITIVES.contains(&s.name.as_str()) {
            continue;
        }
        out.push('\n');
        emit_doc(out, "", &s.description);
        let _ = writeln!(
            out,
            "export const {} = {}",
            schema_name(&s.name),
            scalar_expr(s)
        );
    }
}

fn emit_enums(out: &mut String, api: &Api) {
    for ty in &api.types {
        let ApiType::Enum(e) = ty else { continue };
        let values = e
            .values
            .iter()
            .map(|v| quoted(v.wire_name()))
            .collect::<Vec<_>>()
            .join(", ");
        out.push('\n');
        emit_doc(out, "", &e.description);
        let _ = writeln!(
            out,
            "export const {} = z.enum([{values}])",
            schema_name(&e.name)
        );
    }
}

fn emit_inputs(out: &mut String, api: &Api) {
    let recursive = recursive_inputs(api);

    for ty in &api.types {
        let ApiType::InputObject(i) = ty else {
            continue;
        };
        out.push('\n');
        emit_doc(out, "", &i.description);

        // TypeScript infers a schema's type from its initializer, which it
        // cannot do when the initializer names the schema being defined: the
        // inference is circular and reported as an implicit `any`. Stating the
        // type breaks the cycle. It is deliberately the wide one — the precise
        // type lives in the TypeScript target, and naming it here would make
        // this file, whose only import is `zod`, depend on that one.
        let annotation = if recursive.contains(&i.name) {
            ": z.ZodTypeAny"
        } else {
            ""
        };

        if i.one_of {
            // Each arm admits its own key and nothing else, so a body carrying
            // two variants fails rather than having one of them ignored.
            let _ = writeln!(
                out,
                "export const {}{annotation} = z.union([",
                schema_name(&i.name)
            );
            for f in &i.fields {
                let _ = writeln!(
                    out,
                    "  z.strictObject({{ {}: {} }}),",
                    f.name,
                    field_expr(api, f, true)
                );
            }
            out.push_str("])\n");
            continue;
        }

        let _ = writeln!(
            out,
            "export const {}{annotation} = z.object({{",
            schema_name(&i.name)
        );
        for f in &i.fields {
            emit_doc(out, "  ", &f.description);
            let _ = writeln!(out, "  {}: {},", f.name, field_expr(api, f, false));
        }
        out.push_str("})\n");
    }
}

/// The path-to-schema table and the hook the generated client calls.
///
/// Keyed by path rather than by operation name because the path is what the
/// client has in hand at the call site, and the compiler already guarantees it
/// is unique — two versions of one operation are two paths, so each gets the
/// schema of its own version.
fn emit_registry(out: &mut String, api: &Api) {
    out.push_str("\n/** Input schema for every operation that takes one, keyed by RPC path. */\n");
    out.push_str("export const inputSchemas: Record<string, z.ZodType> = {\n");
    for service in &api.services {
        for op in &service.operations {
            let Some(input) = &op.input else { continue };
            let _ = writeln!(out, "  '{}': {},", op.path, schema_name(input.base_name()));
        }
    }
    out.push_str("}\n");

    out.push_str(
        r#"
/**
 * Check `input` against the operation's declared constraints, throwing zod's own
 * `ZodError` when it does not hold.
 *
 * Pass it to the client as `new RpcClient({ validate: validateInput })` and every
 * call is checked before it leaves the browser. The server checks the same rules
 * from the same declarations, so this only moves the rejection earlier — it
 * cannot accept something the server would refuse.
 *
 * An operation taking no input has no schema and nothing to check.
 */
export function validateInput(path: string, input: unknown): void {
  inputSchemas[path]?.parse(input)
}
"#,
    );
}

/// A scalar as its zod base plus whatever the SDL says about it.
fn scalar_expr(s: &ScalarType) -> String {
    apply_constraints(scalar_base(s), &s.constraints)
}

/// The zod type a scalar carries on the wire, before any of its own rules.
fn scalar_base(s: &ScalarType) -> String {
    match (s.typescript.as_str(), s.openapi_format.as_deref()) {
        // `z.guid()`, not `z.uuid()`: the version and variant nibbles RFC 4122
        // fixes are not fixed in practice. Hand-assigned system ids — a seeded
        // workspace or system user — are accepted by Postgres `::uuid` and by
        // `Uuid::from_u128` alike, and resolve everywhere they are used. Only a
        // strict RFC check would reject them, and rejecting an id the rest of the
        // stack round-trips is a false negative, not a caught bug.
        ("string", Some("uuid")) => "z.guid()".to_string(),
        ("string", Some("date-time")) => "z.iso.datetime()".to_string(),
        ("string", _) => "z.string()".to_string(),
        // An integer format is a real constraint on a JSON number, which is a
        // double until something says otherwise.
        ("number", Some("int32" | "int64")) => "z.number().int()".to_string(),
        ("number", _) => "z.number()".to_string(),
        ("boolean", _) => "z.boolean()".to_string(),
        // The mapping for an unconstrained JSON value; `z.json()` accepts any
        // JSON and, unlike `z.unknown()`, still requires the key to be present.
        ("unknown", _) => "z.json()".to_string(),
        _ => "z.unknown()".to_string(),
    }
}

/// One field's schema: its type, its own constraints, and its nullability.
///
/// `force_present` is for an `@oneOf` arm, where the chosen variant is present
/// even though the SDL field is nullable — that nullability describes the choice,
/// not the value.
fn field_expr(api: &Api, f: &Field, force_present: bool) -> String {
    // With rules of its own, the field spells out the resolved set over the
    // scalar's bare base rather than chaining onto the scalar's schema: zod
    // accumulates refinements, so chaining would keep a bound the field meant to
    // replace — and the Rust side, which resolves per rule, would then be
    // checking something different.
    let expr = match f.constraints.is_empty() {
        true => type_expr(api, &f.ty),
        false => apply_constraints(base_expr(api, &f.ty), &api.resolved_constraints(f)),
    };
    match f.ty.is_nullable() && !force_present {
        // Absent and null are both accepted, matching the Rust side's
        // `#[serde(default)]` and the `field?: T | null` the types file emits.
        true => format!("{expr}.nullish()"),
        false => expr,
    }
}

fn type_expr(api: &Api, ty: &TypeRef) -> String {
    match ty {
        TypeRef::List { inner, .. } => format!("z.array({})", item_expr(api, inner)),
        TypeRef::Named { name, .. } => named_expr(api, name),
    }
}

/// The same shape as [`type_expr`], with a named scalar's own rules left off so
/// the caller can apply the resolved set itself.
fn base_expr(api: &Api, ty: &TypeRef) -> String {
    match ty {
        TypeRef::List { inner, .. } => format!("z.array({})", item_expr(api, inner)),
        TypeRef::Named { name, .. } => match api.find_scalar(name) {
            Some(s) => scalar_base(s),
            None => named_expr(api, name),
        },
    }
}

/// A list item, which carries its own nullability but has no field of its own.
fn item_expr(api: &Api, ty: &TypeRef) -> String {
    let expr = type_expr(api, ty);
    match ty.is_nullable() {
        true => format!("{expr}.nullable()"),
        false => expr,
    }
}

/// The input types that refer to themselves, directly or through others.
///
/// Traverses lists, unlike the Rust emitter's own cycle check: `z.array` gives
/// no relief from an inference cycle the way `Vec` does from an infinite size,
/// so a type reached only through a list is still reached.
fn recursive_inputs(api: &Api) -> BTreeSet<String> {
    let mut recursive = BTreeSet::new();
    for ty in &api.types {
        let ApiType::InputObject(i) = ty else {
            continue;
        };
        let mut seen = BTreeSet::new();
        if reaches_input(api, &i.name, &i.name, &mut seen) {
            recursive.insert(i.name.clone());
        }
    }
    recursive
}

/// Whether `from` can reach `target` by following input-object fields.
fn reaches_input(api: &Api, from: &str, target: &str, seen: &mut BTreeSet<String>) -> bool {
    let Some(ApiType::InputObject(i)) = api.find_type(from) else {
        return false;
    };
    i.fields.iter().any(|f| {
        let base = f.ty.base_name();
        // Checked before `seen`, so a type that reaches itself is still found
        // on the pass that starts from it.
        base == target || (seen.insert(base.to_string()) && reaches_input(api, base, target, seen))
    })
}

fn named_expr(api: &Api, name: &str) -> String {
    match api.find_type(name) {
        // A primitive has no named schema; anything else refers to its own.
        Some(ApiType::Scalar(s)) if PRIMITIVES.contains(&s.name.as_str()) => scalar_expr(s),
        // `z.lazy` frees the emitter from declaration order, and is what lets a
        // recursive input describe itself at all.
        Some(ApiType::InputObject(_)) => format!("z.lazy(() => {})", schema_name(name)),
        Some(_) => schema_name(name),
        None => "z.unknown()".to_string(),
    }
}

/// `@length`, `@range` and `@pattern` as zod refinements.
///
/// `@length` counts characters for a string and elements for a list, which is
/// exactly what zod's `min`/`max` mean on each, so one directive maps onto both
/// without a second spelling.
fn apply_constraints(base: String, c: &Constraints) -> String {
    let mut expr = base;
    if let Some(v) = c.min_length {
        let _ = write!(expr, ".min({v})");
    }
    if let Some(v) = c.max_length {
        let _ = write!(expr, ".max({v})");
    }
    if let Some(v) = c.minimum {
        let _ = write!(expr, ".min({})", number_literal(v));
    }
    if let Some(v) = c.maximum {
        let _ = write!(expr, ".max({})", number_literal(v));
    }
    if let Some(pattern) = &c.pattern {
        // A JS regex literal, anchored exactly as the SDL wrote it. Only `/`
        // needs escaping: the pattern is otherwise the same syntax.
        let _ = write!(expr, ".regex(/{}/)", pattern.replace('/', "\\/"));
    }
    expr
}

/// A bound without a trailing `.0`, since JavaScript has one number type and
/// `min(0.0)` would read as a distinction that does not exist there.
fn number_literal(v: f64) -> String {
    match v.fract() == 0.0 {
        true => format!("{}", v as i64),
        false => format!("{v}"),
    }
}
