//! Rust emitter: wire types, service traits and web bindings. Reads only the
//! IR and the [`Config`].
//!
//! # Three targets
//!
//! The types, the server bindings and the client are emitted separately
//! because their dependencies differ: types need `serde`, the server adds a
//! web framework, the client adds an HTTP stack. A project that only calls the
//! API takes the types and the client and never compiles `axum`.
//!
//! Emitting `rust_server` without `types_path` reproduces the single-file
//! layout, so a project that wants one file is not forced to split.
//!
//! The preamble, router and handler forms come from mustache templates. The
//! built-in ones target `treat` + `axum` and are compiled in; a project on
//! another stack points [`crate::config::RustConfig`] at its own files.
//!
//! # What a handler does, said once
//!
//! A template is stamped out per operation, so anything written into one is
//! repeated in the output as many times as there are operations. The three
//! things worth knowing about the built-in handler are therefore here rather
//! than in the emitted file:
//!
//! - `ApiJson` rejects a malformed body with the `invalid_body` envelope and an
//!   RFC 6901 pointer to the offending field, so no handler parses anything.
//! - A body that parsed but breaks a constraint the SDL declares is still a
//!   body that does not match the operation's input, so it is rejected before
//!   the service is called rather than left for it to rediscover. An operation
//!   with no `input` still validates: `IgnoredAny` accepts any well-formed JSON
//!   and keeps none of it.
//! - Neither half is translated. The operation returns the envelope itself, and
//!   `ApiError` renders the failure envelope, stashing the error in the response
//!   extensions for a logging layer to read.

use std::fmt::Write;

use crate::config::Config;
use crate::error::CompileError;
use crate::ir::*;
use crate::naming::{codes_type_name, pascal_case, snake_case};
use crate::template::{Template, Vars};

const HEADER: &str = "// @generated by graphql-rpcgen. Source of truth: api/**/*.graphql
// DO NOT EDIT MANUALLY.
";

const DEFAULT_PREAMBLE: &str = include_str!("../templates/rust/preamble.mustache");
const DEFAULT_TYPES_PREAMBLE: &str = include_str!("../templates/rust/types_preamble.mustache");
const DEFAULT_SERVER_PREAMBLE: &str = include_str!("../templates/rust/server_preamble.mustache");
const DEFAULT_HANDLER: &str = include_str!("../templates/rust/handler.mustache");
/// An operation with no `input` argument extracts no body, so its handler is a
/// separate form rather than a conditional inside the main one: a flat mustache
/// context has no way to branch.
const DEFAULT_HANDLER_NO_INPUT: &str = include_str!("../templates/rust/handler_no_input.mustache");
const DEFAULT_ROUTER: &str = include_str!("../templates/rust/router.mustache");
/// Streaming and raw-body support, emitted only for an API that has an
/// operation needing it so a plain JSON API compiles none of it.
const DEFAULT_RUNTIME: &str = include_str!("../templates/rust/rpc_runtime.mustache");
const DEFAULT_CONTEXT_RUNTIME: &str = include_str!("../templates/rust/context_runtime.mustache");
/// One handler form per shape a request and its answer can take. Separate
/// templates rather than one with conditionals, for the same reason the
/// no-input form is separate: a flat mustache context cannot branch.
const DEFAULT_HANDLER_SUBSCRIPTION: &str =
    include_str!("../templates/rust/handler_subscription.mustache");
const DEFAULT_HANDLER_SUBSCRIPTION_NO_INPUT: &str =
    include_str!("../templates/rust/handler_subscription_no_input.mustache");
const DEFAULT_HANDLER_RAW_RESPONSE: &str =
    include_str!("../templates/rust/handler_raw_response.mustache");
const DEFAULT_HANDLER_RAW_RESPONSE_NO_INPUT: &str =
    include_str!("../templates/rust/handler_raw_response_no_input.mustache");
const DEFAULT_HANDLER_RAW_REQUEST: &str =
    include_str!("../templates/rust/handler_raw_request.mustache");
const DEFAULT_HANDLER_RAW_BOTH: &str = include_str!("../templates/rust/handler_raw_both.mustache");

/// Variables the preamble template may reference, besides `template_vars`.
///
/// `types_import` is empty for the single-file layout, so the same template
/// serves both arrangements.
const PREAMBLE_VARS: [&str; 3] = ["error_code_enum", "invalid_body_code", "types_import"];
/// Variables the handler template may reference, besides `template_vars`.
///
/// The no-input form sees the same set; `input` is simply empty there, so a
/// project overriding one template can use the same variable names in both.
const HANDLER_VARS: [&str; 11] = [
    "handler",
    "trait_name",
    "input",
    "output",
    "method",
    "path",
    // The `[QueryField; N]` literal a form reading its input from the URL
    // decodes against, and the struct field a raw request writes its body to.
    "query_fields",
    "body_field",
    // The context extractor a session-guarded handler runs, and the argument it
    // then passes on. Both empty for an operation needing no session, so one
    // set of variables serves every form rather than doubling the templates.
    "context_extractor",
    "context_arg",
    // The role gate, run before the service is called so a denial never reaches
    // the method.
    "role_guard",
];
/// Variables the runtime template may reference, besides `template_vars`.
const RUNTIME_VARS: [&str; 2] = ["invalid_body_code", "internal_error_code"];
/// The context runtime interpolates nothing: it names the project's trait and
/// the extractor, both spelled the same in every project.
const CONTEXT_RUNTIME_VARS: [&str; 0] = [];
/// Variables the router template may reference, besides `template_vars`.
const ROUTER_VARS: [&str; 4] = ["service", "module", "trait_name", "routes"];

/// The templates the emitter renders, compiled once per run.
struct Templates {
    preamble: Template,
    /// Streaming and raw-body support, rendered only when something needs it.
    runtime: Template,
    /// The context extractor and its trait, rendered only for an API with a
    /// session-guarded operation.
    context_runtime: Template,
    handler: Template,
    /// Handler form for an operation declaring no `input` argument.
    handler_no_input: Template,
    handler_subscription: Template,
    handler_subscription_no_input: Template,
    handler_raw_response: Template,
    handler_raw_response_no_input: Template,
    handler_raw_request: Template,
    /// Bytes in and bytes out: an operation declaring both `@raw` directions.
    handler_raw_both: Template,
    router: Template,
    /// Project-supplied values merged into every render.
    extra: Vars,
}

impl Templates {
    /// Compile the templates for one target.
    ///
    /// `default_preamble` differs per target: the single-file layout keeps the
    /// original combined preamble, while a split server imports its types.
    fn load(config: &Config, default_preamble: &str) -> Result<Self, CompileError> {
        let extra_names: Vec<&str> = config
            .rust
            .template_vars
            .keys()
            .map(String::as_str)
            .collect();

        let compile = |source: &str,
                       origin: &str,
                       path: &Option<std::path::PathBuf>,
                       base: &[&str]|
         -> Result<Template, CompileError> {
            let mut allowed: Vec<&str> = base.to_vec();
            allowed.extend_from_slice(&extra_names);
            match path {
                Some(path) => Template::from_file(path, &allowed),
                None => Template::compile(source, origin, &allowed),
            }
        };

        Ok(Self {
            preamble: compile(
                default_preamble,
                "<builtin preamble>",
                &config.rust.preamble_template,
                &PREAMBLE_VARS,
            )?,
            handler: compile(
                DEFAULT_HANDLER,
                "<builtin handler>",
                &config.rust.handler_template,
                &HANDLER_VARS,
            )?,
            handler_no_input: compile(
                DEFAULT_HANDLER_NO_INPUT,
                "<builtin no-input handler>",
                &config.rust.handler_no_input_template,
                &HANDLER_VARS,
            )?,
            // The streaming and raw forms have no config hook: they are the
            // built-ins or nothing, until a project asks to replace one.
            runtime: compile(DEFAULT_RUNTIME, "<builtin runtime>", &None, &RUNTIME_VARS)?,
            context_runtime: compile(
                DEFAULT_CONTEXT_RUNTIME,
                "<builtin context runtime>",
                &None,
                &CONTEXT_RUNTIME_VARS,
            )?,
            handler_subscription: compile(
                DEFAULT_HANDLER_SUBSCRIPTION,
                "<builtin subscription handler>",
                &None,
                &HANDLER_VARS,
            )?,
            handler_subscription_no_input: compile(
                DEFAULT_HANDLER_SUBSCRIPTION_NO_INPUT,
                "<builtin no-input subscription handler>",
                &None,
                &HANDLER_VARS,
            )?,
            handler_raw_response: compile(
                DEFAULT_HANDLER_RAW_RESPONSE,
                "<builtin raw-response handler>",
                &None,
                &HANDLER_VARS,
            )?,
            handler_raw_response_no_input: compile(
                DEFAULT_HANDLER_RAW_RESPONSE_NO_INPUT,
                "<builtin no-input raw-response handler>",
                &None,
                &HANDLER_VARS,
            )?,
            handler_raw_request: compile(
                DEFAULT_HANDLER_RAW_REQUEST,
                "<builtin raw-request handler>",
                &None,
                &HANDLER_VARS,
            )?,
            handler_raw_both: compile(
                DEFAULT_HANDLER_RAW_BOTH,
                "<builtin raw handler>",
                &None,
                &HANDLER_VARS,
            )?,
            router: compile(
                DEFAULT_ROUTER,
                "<builtin router>",
                &config.rust.router_template,
                &ROUTER_VARS,
            )?,
            extra: config.rust.template_vars.clone(),
        })
    }

    /// A render context seeded with the project's own variables.
    fn vars(&self, pairs: &[(&str, &str)]) -> Vars {
        let mut vars = self.extra.clone();
        for (key, value) in pairs {
            vars.insert((*key).to_string(), (*value).to_string());
        }
        vars
    }
}

/// Server bindings, and the wire types too unless they live elsewhere.
///
/// With no `types_path` configured this is the whole API in one file, which is
/// the layout a project gets before it splits anything.
pub fn generate(api: &Api, config: &Config) -> Result<String, CompileError> {
    let split = config.rust.types_path.is_some();
    let default_preamble = if split {
        DEFAULT_SERVER_PREAMBLE
    } else {
        DEFAULT_PREAMBLE
    };
    let templates = Templates::load(config, default_preamble)?;

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(&templates.preamble.render(&templates.vars(&[
        ("error_code_enum", crate::semantic::ERROR_CODE_ENUM),
        ("invalid_body_code", &invalid_body_code()),
        (
            "types_import",
            &glob_import(config.rust.types_path.as_deref()),
        ),
    ]))?);

    // Streaming and raw bodies bring their own imports and helpers, so they are
    // emitted only for an API that has an operation needing them.
    if api
        .services
        .iter()
        .flat_map(|service| &service.operations)
        .any(needs_runtime)
    {
        out.push_str(&templates.runtime.render(&templates.vars(&[
            ("invalid_body_code", &invalid_body_code()),
            ("internal_error_code", &internal_error_code()),
        ]))?);
    }

    // The extractor and the trait it needs, for an API that guards anything on a
    // session. One that authenticates elsewhere compiles neither.
    if api
        .services
        .iter()
        .flat_map(|service| &service.operations)
        .any(needs_context)
    {
        out.push_str(&templates.context_runtime.render(&templates.vars(&[]))?);
    }

    // Without a types module of their own, the types belong here: the server
    // file is then self-contained, exactly as before the split existed.
    if !split {
        emit_types(&mut out, api);
    }

    for service in &api.services {
        emit_service(&mut out, api, service, &templates)?;
    }

    Ok(out)
}

/// Wire types alone: no service traits, no transport, no web framework.
pub fn generate_types(api: &Api, config: &Config) -> Result<String, CompileError> {
    let templates = Templates::load(config, DEFAULT_TYPES_PREAMBLE)?;

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(&templates.preamble.render(&templates.vars(&[
        ("error_code_enum", crate::semantic::ERROR_CODE_ENUM),
        ("invalid_body_code", &invalid_body_code()),
        ("types_import", ""),
    ]))?);
    emit_types(&mut out, api);

    Ok(out)
}

/// Every declared type, in the IR's sorted order, then the error vocabulary:
/// the registry enum, and one error set per operation.
///
/// Both belong here rather than next to the service traits because both sides
/// name them — the server answers with those codes and the client branches on
/// them — and only the types module is shared by both.
fn emit_types(out: &mut String, api: &Api) {
    emit_pattern_statics(out, api);

    for ty in &api.types {
        match ty {
            ApiType::Scalar(s) if s.rust_newtype => emit_scalar_newtype(out, s),
            ApiType::Scalar(_) => {}
            ApiType::Enum(e) => emit_enum(out, e),
            ApiType::Object(o) => emit_object(out, api, o),
            ApiType::InputObject(i) => emit_input_object(out, api, i),
            ApiType::Union(u) => emit_union(out, u),
        }
    }

    emit_error_sets(out, api);
}

/// Rust path of the registry code a constraint violation reports.
///
/// The template needs the code by name rather than as a literal, so renaming the
/// registry value in the SDL cannot leave a stale string in the preamble.
fn invalid_body_code() -> String {
    format!(
        "{}::{}",
        crate::semantic::ERROR_CODE_ENUM,
        crate::semantic::CODE_INVALID_BODY
    )
}

/// Rust path of the registry code the runtime reports its own faults with.
fn internal_error_code() -> String {
    format!(
        "{}::{}",
        crate::semantic::ERROR_CODE_ENUM,
        crate::semantic::CODE_INTERNAL_ERROR
    )
}

/// Whether an operation needs the streaming and raw-body runtime.
///
/// A plain JSON operation reads its input from the body and answers with the
/// envelope, which the preamble already covers.
fn needs_runtime(op: &Operation) -> bool {
    op.kind == OperationKind::Subscription || op.raw_request.is_some() || op.raw_response.is_some()
}

/// Whether an operation needs the request-context runtime.
fn needs_context(op: &Operation) -> bool {
    op.auth.has_context()
}

/// A glob re-export of the types module, or nothing when they are in this file.
///
/// `pub use` rather than `use`: with the types in one file, a consumer wrote
/// `use generated_api::generated::*` and got both the types and the traits.
/// Re-exporting keeps that true after the split, so splitting the crate is not
/// a breaking change for callers.
///
/// Emitted with a trailing newline so the templates read the same either way.
fn glob_import(types_path: Option<&str>) -> String {
    match types_path {
        Some(path) => format!("\npub use {path}::*;\n"),
        None => String::new(),
    }
}

fn emit_doc(out: &mut String, indent: &str, description: &Option<String>) {
    let Some(text) = description else { return };
    for line in text.lines() {
        let _ = writeln!(out, "{indent}/// {line}");
    }
}

/// A transparent wrapper around a scalar's Rust representation.
///
/// `#[serde(transparent)]` keeps the wire format identical to the inner type,
/// so the newtype is a compile-time distinction only.
///
/// The conversions come from `derive_more` rather than hand-written impls.
/// `Deref` is deliberately not among them: it would auto-deref the whole inner
/// API onto the wrapper — `clan_id.as_u128()` — which is exactly the leak the
/// newtype exists to prevent. `AsRef` offers the same access explicitly.
fn emit_scalar_newtype(out: &mut String, s: &ScalarType) {
    let name = &s.name;
    let inner = &s.rust;

    out.push('\n');
    emit_doc(out, "", &s.description);
    // `Copy` only holds when the wrapped type is itself `Copy`: a UUID-backed
    // id is, a String-backed one is not.
    let copy = if s.rust_copy { "Copy, " } else { "" };
    // `Eq`, `Ord` and `Hash` follow the inner type, and a float has none of the
    // three. Deriving them unconditionally made `rustRange: true` — the setting
    // that exists for numeric newtypes — a guaranteed rustc failure over `f64`.
    let ordering = if is_rust_float(inner) {
        "PartialOrd"
    } else {
        "Eq, PartialOrd, Ord, Hash"
    };
    let _ = writeln!(
        out,
        "#[derive(\n    Debug, Clone, {copy}PartialEq, {ordering},\n    \
         Serialize, Deserialize,\n    AsRef, Display, From, Into,\n)]"
    );
    out.push_str("#[serde(transparent)]\n");
    let _ = writeln!(out, "pub struct {name}(pub {inner});");

    // A constraint on a field of this type has to reach through the wrapper, and
    // `validator` only knows the types it ships impls for. The wire form of a
    // newtype is its inner value, so that is what the rules are measured
    // against: directly for a string, through `Display` otherwise — the
    // rendering a `uuid::Uuid` or a number has on the wire.
    let subject = match inner.as_str() {
        "String" => "&self.0".to_string(),
        _ => "&self.to_string()".to_string(),
    };
    let _ = writeln!(
        out,
        "\nimpl validator::ValidateLength<u64> for {name} {{\n    \
         fn length(&self) -> Option<u64> {{\n        \
         validator::ValidateLength::length({subject})\n    }}\n}}"
    );
    let _ = writeln!(
        out,
        "\nimpl validator::ValidateRegex for {name} {{\n    \
         fn validate_regex(&self, regex: impl validator::AsRegex) -> bool {{\n        \
         validator::ValidateRegex::validate_regex({subject}, regex)\n    }}\n}}"
    );

    // `@range` compares numbers, and the validator ships those impls only for
    // its own primitives — a numeric newtype opts in with `rustRange` and gets
    // the same reach-through adapter.
    if s.rust_range {
        let _ = writeln!(
            out,
            "\nimpl validator::ValidateRange<{inner}> for {name} {{\n    \
             fn greater_than(&self, other: {inner}) -> Option<bool> {{\n        \
             Some(self.0 > other)\n    }}\n    \
             fn less_than(&self, other: {inner}) -> Option<bool> {{\n        \
             Some(self.0 < other)\n    }}\n}}"
        );
    }
}

fn emit_enum(out: &mut String, e: &EnumType) {
    if e.name == crate::semantic::ERROR_CODE_ENUM {
        emit_error_code_enum(out, e);
        return;
    }

    out.push('\n');
    emit_doc(out, "", &e.description);
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n");
    let _ = writeln!(out, "pub enum {} {{", e.name);
    for v in &e.values {
        emit_doc(out, "    ", &v.description);
        // The Rust variant is PascalCase while the wire carries the SDL
        // spelling, or whatever `@variant(tag:)` overrode it with, so the wire
        // name is pinned explicitly rather than left to a rename rule.
        let _ = writeln!(out, "    #[serde(rename = {:?})]", v.wire_name());
        let _ = writeln!(out, "    {},", pascal_case(&v.name));
    }
    out.push_str("}\n");
}

/// The error registry, as a `treat` code enum.
///
/// Variants keep their SDL spelling so the Rust name and the wire code are the
/// same string, which is how the portal's own `PortalErrorCode` is written.
/// `#[derive(ApiErrorCode)]` supplies `Display`, `From<ErrorCode> for
/// ApiError<ErrorCode>` and the declared `#[message(...)]`.
fn emit_error_code_enum(out: &mut String, e: &EnumType) {
    out.push('\n');
    emit_doc(out, "", &e.description);
    out.push_str("#[allow(non_camel_case_types)]\n");
    out.push_str(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ApiErrorCode)]\n",
    );
    let _ = writeln!(out, "pub enum {} {{", e.name);
    for v in &e.values {
        emit_doc(out, "    ", &v.description);
        // The default message travels with the code, so a handler that has
        // nothing to add does not restate it at the call site.
        let _ = writeln!(out, "    #[message({:?})]", default_message(&v.name));
        let _ = writeln!(out, "    {},", v.name);
    }
    out.push_str("}\n");
}

/// Human-readable default for a code: `clan_not_found` -> `clan not found`.
fn default_message(code: &str) -> String {
    code.replace('_', " ")
}

/// One error set per operation, in a single `error_set!` declaration.
///
/// The flat registry says what the API can return; it does not say what *this*
/// operation can, so without a per-operation set a handler could answer with any
/// code in it and `@throws` would be documentation nobody checks.
///
/// A variant is named after the registry code and carries that code as its
/// `#[display]`, so the Rust name and the string on the wire stay the same
/// vocabulary `errors.graphql` declares.
///
/// Each set also gets the two impls `Narrow` needs to report a flat `Failure`
/// through it: `TryFrom` for the codes it declares, and `Undeclared` for what to
/// answer with for the codes it does not.
fn emit_error_sets(out: &mut String, api: &Api) {
    out.push_str(
        "\n// Each set is one operation's `@throws`, plus the codes the runtime emits\n\
         // before the operation runs. Anything else is a compile error at the handler.\n",
    );
    out.push_str("error_set! {\n");
    for service in &api.services {
        for op in &service.operations {
            emit_operation_error_set(out, service, op);
        }
    }
    out.push_str("}\n");

    for service in &api.services {
        for op in &service.operations {
            emit_error_set_narrowing(out, service, op);
        }
    }
}

/// The runtime half of an operation's declaration: which registry codes convert
/// into its set, and what an undeclared one becomes.
fn emit_error_set_narrowing(out: &mut String, service: &Service, op: &Operation) {
    let registry = crate::semantic::ERROR_CODE_ENUM;
    let set = codes_type_name(&service.name, &op.name);

    let _ = writeln!(out, "\nimpl TryFrom<{registry}> for {set} {{");
    let _ = writeln!(out, "    type Error = {registry};");
    let _ = writeln!(
        out,
        "    fn try_from(code: {registry}) -> Result<Self, Self::Error> {{"
    );
    out.push_str("        match code {\n");
    for code in op.error_codes() {
        let _ = writeln!(
            out,
            "            {registry}::{code} => Ok(Self::{}),",
            code_type_name(code)
        );
    }
    out.push_str("            other => Err(other),\n        }\n    }\n}\n");

    let _ = writeln!(
        out,
        "\nimpl Undeclared for {set} {{\n    const UNDECLARED: Self = Self::{};\n}}",
        code_type_name(crate::semantic::CODE_INTERNAL_ERROR)
    );
}

/// One operation's set, as an `error_set!` member.
fn emit_operation_error_set(out: &mut String, service: &Service, op: &Operation) {
    let _ = writeln!(
        out,
        "    /// Error codes `{}.{}` may answer with.",
        service.name, op.name
    );
    // `treat` requires a code to be `Clone`; the rest of `ApiErrorCode` is
    // satisfied by what `error_set!` derives on its own.
    out.push_str("    #[derive(Clone)]\n");
    let _ = writeln!(
        out,
        "    {} := {{",
        codes_type_name(&service.name, &op.name)
    );
    for code in op.error_codes() {
        let _ = writeln!(
            out,
            "        #[display(\"{code}\")] {},",
            code_type_name(code)
        );
    }
    out.push_str("    }\n");
}

/// The Rust type standing for a wire code: `clan_not_found` -> `ClanNotFound`.
fn code_type_name(code: &str) -> String {
    pascal_case(code)
}

fn emit_object(out: &mut String, api: &Api, o: &ObjectType) {
    out.push('\n');
    emit_doc(out, "", &o.description);
    out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    let _ = writeln!(out, "pub struct {} {{", o.name);
    for f in &o.fields {
        emit_struct_field(out, api, &o.name, f);
    }
    out.push_str("}\n");
}

fn emit_input_object(out: &mut String, api: &Api, i: &InputObjectType) {
    out.push('\n');
    emit_doc(out, "", &i.description);

    if i.one_of {
        // Exactly-one-of maps to serde's default representation: renamed
        // newtype variants. On the wire that is exactly the one-key object
        // {"card": {...}}, and deserialization of the tagged form rejects a
        // body that names two arms or any arm that was not chosen —
        // exclusivity is the wire format, not a check. `#[serde(untagged)]`
        // would change what matches and must not be added.
        out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
        let _ = writeln!(out, "pub enum {} {{", i.name);
        for f in &i.fields {
            emit_doc(out, "    ", &f.description);
            let _ = writeln!(out, "    #[serde(rename = {:?})]", f.name);
            let inner = one_of_arm_type(api, &i.name, &f.ty);
            let _ = writeln!(out, "    {}({inner}),", pascal_case(&f.name));
        }
        out.push_str("}\n");
        emit_one_of_validate(out, api, i);
        return;
    }

    out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Validate)]\n");
    let _ = writeln!(out, "pub struct {} {{", i.name);
    for f in &i.fields {
        emit_struct_field_validated(out, api, &i.name, f);
    }
    out.push_str("}\n");
}

/// `Validate` for an `@oneOf` input, which is an enum and so out of reach of
/// the derive. The chosen arm is checked exactly like an ordinary field of the
/// same name: a nested input object validates itself, and a scalar is measured
/// through the same validator traits a `#[validate(...)]` attribute calls —
/// with the same rules every other target resolves through
/// `resolved_constraints`, so browser and server keep checking one check.
fn emit_one_of_validate(out: &mut String, api: &Api, i: &InputObjectType) {
    let _ = writeln!(out, "\nimpl Validate for {} {{", i.name);
    out.push_str("    fn validate(&self) -> Result<(), validator::ValidationErrors> {\n");
    out.push_str("        match self {\n");
    for f in &i.fields {
        let variant = pascal_case(&f.name);
        let nested = matches!(
            api.find_type(f.ty.base_name()),
            Some(ApiType::InputObject(_))
        );
        match nested {
            true => {
                let _ = writeln!(
                    out,
                    "            Self::{variant}(value) => value.validate(),"
                );
            }
            false => {
                let _ = writeln!(out, "            Self::{variant}(value) => {{");
                out.push_str(
                    "                let mut errors = validator::ValidationErrors::new();\n",
                );
                for rule in arm_validation_rules(api, &i.name, f) {
                    let _ = writeln!(out, "                {rule}");
                }
                out.push_str(
                    "                if errors.is_empty() {\n                    Ok(())\n                } else {\n                    Err(errors)\n                }\n",
                );
                out.push_str("            }\n");
            }
        }
    }
    out.push_str("        }\n    }\n}\n");
}

/// One check an `@oneOf` arm runs against its value, in the shape the
/// `Validate` derive would emit for an ordinary field of the same name: the
/// same trait call, the same message, and the arm's key as the field name in
/// the resulting errors, so a violation points at the arm.
fn arm_validation_rules(api: &Api, owner: &str, f: &Field) -> Vec<String> {
    let c = api.resolved_constraints(f);
    let mut rules: Vec<String> = Vec::new();

    if c.min_length.is_some() || c.max_length.is_some() {
        let bounds = option_args(c.min_length, c.max_length, |v| v.to_string());
        let message = format!(
            "length must be {}",
            describe(c.min_length, c.max_length, |v| v.to_string())
        );
        rules.push(format!(
            "if !validator::ValidateLength::validate_length(value, {bounds}, None) {{\n                    errors.add({f_name:?}, validator::ValidationError::new(\"length\").with_message({message:?}.into()));\n                }}",
            f_name = f.name,
        ));
    }

    if c.minimum.is_some() || c.maximum.is_some() {
        let render = |v: f64| number_literal(api, f, v);
        let bounds = option_args(c.minimum, c.maximum, render);
        let message = format!("must be {}", describe(c.minimum, c.maximum, render));
        rules.push(format!(
            "if !validator::ValidateRange::validate_range(value, {bounds}, None, None) {{\n                    errors.add({f_name:?}, validator::ValidationError::new(\"range\").with_message({message:?}.into()));\n                }}",
            f_name = f.name,
        ));
    }

    if let Some(name) = pattern_static_name(api, owner, f) {
        let message = format!("must match {}", c.pattern.as_deref().unwrap_or_default());
        rules.push(format!(
            "if !matches_pattern(&{name}, value) {{\n                    errors.add({f_name:?}, validator::ValidationError::new(\"regex\").with_message({message:?}.into()));\n                }}",
            f_name = f.name,
        ));
    }

    rules
}

/// `Some(a), Some(b)` in call-argument position, keeping only the bounds that
/// were declared. Positional on purpose: Rust does not allow a positional
/// argument after a named one, and the validator calls end in more of them.
fn option_args<T: Copy>(min: Option<T>, max: Option<T>, render: impl Fn(T) -> String) -> String {
    format!(
        "{}, {}",
        min.map(|v| format!("Some({})", render(v)))
            .unwrap_or_else(|| "None".to_string()),
        max.map(|v| format!("Some({})", render(v)))
            .unwrap_or_else(|| "None".to_string())
    )
}

/// An input field, which carries its constraints as `#[validate(..)]`.
fn emit_struct_field_validated(out: &mut String, api: &Api, owner: &str, f: &Field) {
    emit_doc(out, "    ", &f.description);
    emit_validate_attr(out, api, owner, f);
    emit_field_body(out, api, owner, f);
}

fn emit_struct_field(out: &mut String, api: &Api, owner: &str, f: &Field) {
    emit_doc(out, "    ", &f.description);
    emit_field_body(out, api, owner, f);
}

fn emit_field_body(out: &mut String, api: &Api, owner: &str, f: &Field) {
    let rust_name = snake_case(&f.name);
    if rust_name != f.name {
        let _ = writeln!(out, "    #[serde(rename = {:?})]", f.name);
    }
    if f.ty.is_nullable() {
        // Absent and null are treated alike, and None is omitted on the wire
        // so optional fields do not appear as explicit nulls.
        out.push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
    } else if api.is_binary(f.ty.base_name()) {
        // A raw request's payload is the body, never a member of the object the
        // other fields travel in. `default` is what lets the server build the
        // input from the query string before assigning the body it just read;
        // `skip_serializing` is what keeps the client from putting megabytes of
        // byte array in the query string it builds from the same struct.
        out.push_str("    #[serde(default, skip_serializing)]\n");
    }
    let _ = writeln!(
        out,
        "    pub {rust_name}: {},",
        field_rust_type(api, owner, &f.ty)
    );
}

/// Name of the `LazyLock<Regex>` static holding a field's `@pattern`.
///
/// A pattern declared on a scalar is compiled once and shared by every field of
/// that type; one written on a field gets its own static.
fn pattern_static_name(api: &Api, owner: &str, f: &Field) -> Option<String> {
    if f.constraints.pattern.is_some() {
        // Prefixed to keep the two sources of a static apart: a scalar named
        // `UserName` and a field `User.name` both used to reach for
        // `USER_NAME_PATTERN`, and the file declared it twice.
        return Some(format!(
            "FIELD_{}_{}_PATTERN",
            snake_case(owner).to_uppercase(),
            snake_case(&f.name).to_uppercase()
        ));
    }
    let scalar = api.find_scalar(f.ty.base_name())?;
    if matches!(f.ty, TypeRef::List { .. }) || scalar.constraints.pattern.is_none() {
        return None;
    }
    Some(scalar_pattern_name(&scalar.name))
}

/// Name of the static holding a scalar's own `@pattern`, shared by every field
/// of that type. Spelled here rather than at both ends: the definition and the
/// reference are emitted by different functions, and a name built twice is a
/// name that can be built two ways.
fn scalar_pattern_name(scalar: &str) -> String {
    format!("SCALAR_{}_PATTERN", snake_case(scalar).to_uppercase())
}

/// Every `@pattern` in the API, as a lazily compiled regex and the check that
/// reads it.
///
/// Compiling at first use rather than per request is what makes a pattern
/// constraint free to declare. A pattern that does not compile is kept as
/// `None` and rejects every value: `graphql-rpcgen` compiles each one before
/// emitting it, so that branch is a generator bug, and rejecting is the safe
/// side of one — the alternative admits input nothing checked.
fn emit_pattern_statics(out: &mut String, api: &Api) {
    let mut statics: Vec<(String, String)> = Vec::new();

    for ty in &api.types {
        if let ApiType::Scalar(s) = ty {
            if let Some(pattern) = &s.constraints.pattern {
                statics.push((scalar_pattern_name(&s.name), pattern.clone()));
            }
        }
        let ApiType::InputObject(i) = ty else {
            continue;
        };
        for f in &i.fields {
            // Both halves come from the same declaration: `pattern_static_name`
            // answers for exactly the fields that carry a `@pattern`.
            if let (Some(pattern), Some(name)) =
                (&f.constraints.pattern, pattern_static_name(api, &i.name, f))
            {
                statics.push((name, pattern.clone()));
            }
        }
    }

    for (name, pattern) in statics {
        let message = format!("must match {pattern}");
        let _ = writeln!(
            out,
            "\nstatic {name}: LazyLock<Option<Regex>> =\n    \
             LazyLock::new(|| Regex::new({pattern:?}).ok());"
        );
        let _ = writeln!(
            out,
            "\n/// `#[validate(custom(..))]` for every field carrying `{name}`.\n\
             fn {check}<T: validator::ValidateRegex + ?Sized>(\n    \
             value: &T,\n\
             ) -> Result<(), validator::ValidationError> {{\n    \
             match matches_pattern(&{name}, value) {{\n        \
             true => Ok(()),\n        \
             false => Err(validator::ValidationError::new(\"regex\").with_message({message:?}.into())),\n    \
             }}\n}}",
            check = pattern_check_name(&name),
        );
    }
}

/// Name of the `custom` function that checks one `@pattern` static.
fn pattern_check_name(static_name: &str) -> String {
    format!("check_{}", static_name.to_lowercase())
}

/// `#[validate(..)]` for one input field, or nothing when it has no rules.
///
/// The message travels to the client verbatim: `treat` turns each violation into
/// one `errors[]` entry with a JSON Pointer to the field, so a caller learns
/// which field was wrong and what was expected without reading the SDL.
fn emit_validate_attr(out: &mut String, api: &Api, owner: &str, f: &Field) {
    let c = api.resolved_constraints(f);
    let mut rules: Vec<String> = Vec::new();

    // Every message is written with `{:?}`, so a pattern's own backslashes reach
    // the generated file as a Rust string literal rather than as escapes Rust
    // tries to interpret itself.
    if c.min_length.is_some() || c.max_length.is_some() {
        let bounds = bound_args(c.min_length, c.max_length, |v| v.to_string());
        let noun = match matches!(f.ty, TypeRef::List { .. }) {
            true => "element count",
            false => "length",
        };
        let message = format!(
            "{noun} must be {}",
            describe(c.min_length, c.max_length, |v| v.to_string())
        );
        rules.push(format!("length({bounds}, message = {message:?})"));
    }

    if c.minimum.is_some() || c.maximum.is_some() {
        let render = |v: f64| number_literal(api, f, v);
        let bounds = bound_args(c.minimum, c.maximum, render);
        let message = format!("must be {}", describe(c.minimum, c.maximum, render));
        rules.push(format!("range({bounds}, message = {message:?})"));
    }

    // `custom` rather than `regex(path = ..)`: the static is an `Option`, so
    // that a pattern which failed to compile rejects instead of panicking, and
    // `validator`'s own regex rule cannot read one.
    if let Some(name) = pattern_static_name(api, owner, f) {
        rules.push(format!("custom(function = {})", pattern_check_name(&name)));
    }

    // An input nested inside another carries its own rules, and `nested` is what
    // walks into it — including through a list, so `/list/3/name` is reachable.
    if matches!(
        api.find_type(f.ty.base_name()),
        Some(ApiType::InputObject(_))
    ) {
        rules.push("nested".to_string());
    }

    if !rules.is_empty() {
        let _ = writeln!(out, "    #[validate({})]", rules.join(", "));
    }
}

/// `min = a, max = b`, keeping only the bounds that were declared.
fn bound_args<T: Copy>(min: Option<T>, max: Option<T>, render: impl Fn(T) -> String) -> String {
    [min.map(|v| ("min", v)), max.map(|v| ("max", v))]
        .into_iter()
        .flatten()
        .map(|(key, v)| format!("{key} = {}", render(v)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// The bounds in prose, for the message a caller reads.
fn describe<T: Copy>(min: Option<T>, max: Option<T>, render: impl Fn(T) -> String) -> String {
    match (min, max) {
        (Some(a), Some(b)) => format!("between {} and {}", render(a), render(b)),
        (Some(a), None) => format!("at least {}", render(a)),
        (None, Some(b)) => format!("at most {}", render(b)),
        (None, None) => String::new(),
    }
}

/// A `@range` bound spelled so it has the field's own Rust type.
///
/// `validator` compares the bound against the value directly, so an integer
/// field needs `0` and a floating-point one `0.0`: the literal is the type.
fn number_literal(api: &Api, f: &Field, v: f64) -> String {
    let float = api
        .find_scalar(f.ty.base_name())
        .is_some_and(|s| is_rust_float(&s.rust));
    match float {
        true => format!("{v:?}"),
        false => format!("{}", v as i64),
    }
}

/// Whether a scalar's Rust representation is one of the two floating-point
/// primitives, which decides both how a `@range` bound is spelled and which
/// traits a newtype over it can derive.
///
/// Named exactly rather than matched by prefix: a project mapping a scalar to
/// `foo::Bar` is not asking for a float, and the prefix test said it was.
fn is_rust_float(rust: &str) -> bool {
    matches!(rust, "f32" | "f64")
}

/// The type one `@oneOf` arm carries.
///
/// Non-null, because the chosen arm is present whatever the SDL field's
/// nullability says about the choice — that nullability describes the choice.
/// Boxed when the arm refers back to the enum, which is the same relief
/// [`field_rust_type`] gives an ordinary struct field: without it an input that
/// describes itself has no finite size.
fn one_of_arm_type(api: &Api, owner: &str, ty: &TypeRef) -> String {
    let inner = rust_type_non_null(api, ty);
    match matches!(ty, TypeRef::Named { name, .. } if name == owner || api.reaches(name, owner)) {
        true => format!("Box<{inner}>"),
        false => inner,
    }
}

fn emit_union(out: &mut String, u: &UnionType) {
    out.push('\n');
    emit_doc(out, "", &u.description);
    out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    let _ = writeln!(out, "#[serde(tag = {:?})]", u.discriminator);
    let _ = writeln!(out, "pub enum {} {{", u.name);
    for member in &u.members {
        // Internally tagged newtype variants flatten the member's fields
        // alongside the tag, giving {"kind":"CardPayment","last4":"4242"}.
        if member.tag != member.name {
            let _ = writeln!(out, "    #[serde(rename = {:?})]", member.tag);
        }
        let _ = writeln!(out, "    {}({}),", member.name, member.name);
    }
    out.push_str("}\n");
}

fn emit_service(
    out: &mut String,
    api: &Api,
    service: &Service,
    templates: &Templates,
) -> Result<(), CompileError> {
    let trait_name = format!("{}Service", service.name);
    let module = snake_case(&service.name);

    out.push('\n');
    emit_doc(out, "", &service.description);
    out.push_str("#[async_trait::async_trait]\n");
    let _ = writeln!(
        out,
        "pub trait {trait_name}: Clone + Send + Sync + 'static {{"
    );
    // Only a service with something to guard names a context, so one that
    // guards nothing is the trait it always was.
    if service.operations.iter().any(needs_context) {
        out.push_str(
            "    /// The caller, resolved from the request before a guarded operation runs.\n\
             ///\n\
             /// An associated type rather than a name from this crate: resolving a session\n\
             /// is the implementation's, and it lives above this one.\n\
             \x20   type Ctx: FromRequestContext;\n\n",
        );
    }
    for op in &service.operations {
        emit_doc(out, "    ", &op.description);
        let error = codes_type_name(&service.name, &op.name);
        // An operation with no `input` argument takes no parameter: there is
        // no placeholder value for an implementation to receive and ignore.
        let arg = match &op.input {
            Some(input) => format!(", input: {}", rust_type(api, input)),
            None => String::new(),
        };
        // The context comes first because it is the caller, not the request: it
        // reads as the subject of the call, and it is the parameter every
        // session-guarded operation shares.
        let ctx = context_param(op);
        // The failure half is `ApiError<Codes>`, which names the codes the
        // operation may use and is what `?` and treat's `wrap_api_error` family
        // produce. The success half is whatever this operation actually
        // answers with — see [`success_type`].
        let _ = writeln!(
            out,
            "    async fn {}(&self{ctx}{arg}) -> Result<{}, ApiError<{error}>>;",
            snake_case(&op.name),
            success_type(api, op)
        );
    }
    out.push_str("}\n");

    // The route list is assembled here rather than in the template: a flat
    // string context has nothing for a mustache section to iterate.
    let mut routes = String::new();
    for op in &service.operations {
        // Everything is POST except a subscription, which is opened by an
        // `EventSource` and so can only be a GET.
        let verb = if op.kind == OperationKind::Subscription {
            "get"
        } else {
            "post"
        };
        let _ = writeln!(
            routes,
            "        .route(\"{}\", {verb}({module}_{}::<S>))",
            op.path,
            snake_case(&op.name)
        );
    }

    out.push_str(&templates.router.render(&templates.vars(&[
        ("service", &service.name),
        ("module", &module),
        ("trait_name", &trait_name),
        ("routes", &routes),
    ]))?);

    for op in &service.operations {
        let handler = format!("{module}_{}", snake_case(&op.name));
        let template = handler_template(templates, op);
        let input = match &op.input {
            Some(input) => rust_type(api, input),
            None => String::new(),
        };
        // Empty for a form that reads neither: rendering a variable a template
        // never mentions costs nothing, and it keeps one set of vars per form.
        let body_field = match api.body_field(op) {
            Some(f) => snake_case(&f.name),
            None => String::new(),
        };
        // Prefixed onto the call's argument list. The separator depends on
        // whether an `input` follows, since a trailing comma before `)` is only
        // valid where another argument was going to be.
        let context_arg = match (op.auth.has_context(), op.input.is_some()) {
            (true, true) => "&ctx, ".to_string(),
            (true, false) => "&ctx".to_string(),
            (false, _) => String::new(),
        };
        out.push_str(&template.render(&templates.vars(&[
            ("handler", &handler),
            ("trait_name", &trait_name),
            ("input", &input),
            ("output", &rust_type(api, &op.output)),
            ("method", &snake_case(&op.name)),
            ("path", &op.path),
            ("query_fields", &query_fields_literal(api, op)),
            ("body_field", &body_field),
            ("context_extractor", &context_extractor(op)),
            ("context_arg", &context_arg),
            ("role_guard", &role_guard(op)),
        ]))?);
    }

    Ok(())
}

/// What a service method hands back when it succeeds.
///
/// Three shapes, because three things can be answered with: a stream of events,
/// a body of bytes, or the JSON envelope every other operation returns.
fn success_type(api: &Api, op: &Operation) -> String {
    if op.kind == OperationKind::Subscription {
        // The output type is one event, not the stream, so the stream is named
        // here rather than in the SDL.
        return format!("EventStream<{}>", rust_type(api, &op.output));
    }
    if op.raw_response.is_some() {
        // The declared type is the binary scalar, which says the body is bytes
        // and nothing more; `RawBody` is what carries them plus the headers
        // that describe them.
        return "RawBody".to_string();
    }
    format!("ApiResponse<{}>", rust_type(api, &op.output))
}

/// The context parameter a service method takes, or nothing.
///
/// Empty for every requirement but `session`: a token names no user and a
/// public operation has no caller to describe, so there would be nothing to
/// pass. The type is the trait's own associated `Ctx`, which is what keeps the
/// generated crate from having to name a type that lives above it.
fn context_param(op: &Operation) -> String {
    if op.auth.has_context() {
        ", ctx: &Self::Ctx".to_string()
    } else {
        String::new()
    }
}

/// The extractor line a session-guarded handler runs.
///
/// Names the context through the service trait rather than directly, so the
/// handler stays generic over `S` and the concrete type is the implementation's
/// business.
fn context_extractor(op: &Operation) -> String {
    if op.auth.has_context() {
        "Ctx(ctx): Ctx<S::Ctx>,\n    ".to_string()
    } else {
        String::new()
    }
}

/// The role gate, emitted between the extractors and the call.
fn role_guard(op: &Operation) -> String {
    match (&op.role, op.auth.has_context()) {
        (Some(role), true) => format!(
            "    if let Err(response) = ctx.require_role({role:?}) {{\n        \
             return response;\n    }}\n"
        ),
        _ => String::new(),
    }
}

/// The handler form for one operation: where its input comes from, and what
/// its answer is.
fn handler_template<'a>(templates: &'a Templates, op: &Operation) -> &'a Template {
    let has_input = op.input.is_some();
    match (
        op.kind,
        has_input,
        op.raw_request.is_some(),
        op.raw_response.is_some(),
    ) {
        (OperationKind::Subscription, true, _, _) => &templates.handler_subscription,
        (OperationKind::Subscription, false, _, _) => &templates.handler_subscription_no_input,
        // A raw request always has an input: its payload is a field of one.
        (_, _, true, true) => &templates.handler_raw_both,
        (_, _, true, false) => &templates.handler_raw_request,
        (_, true, false, true) => &templates.handler_raw_response,
        (_, false, false, true) => &templates.handler_raw_response_no_input,
        (_, true, false, false) => &templates.handler,
        (_, false, false, false) => &templates.handler_no_input,
    }
}

/// The `[QueryField; N]` literal a handler decodes its query string against.
///
/// Only the operations that read their input from the URL render it; for the
/// rest it is an unused variable in a template that never mentions it.
fn query_fields_literal(api: &Api, op: &Operation) -> String {
    let fields = api.query_fields(op);
    if fields.is_empty() {
        return "[]".to_string();
    }
    let mut out = String::from("[\n");
    for f in fields {
        let _ = writeln!(
            out,
            "        QueryField {{ name: {:?}, kind: QueryKind::{}, list: {} }},",
            f.name,
            query_kind(api, f),
            matches!(f.ty, TypeRef::List { .. })
        );
    }
    out.push_str("    ]");
    out
}

/// How one field's text in the query string becomes a JSON value.
///
/// Read off the field's declared type, because the text cannot say: `2` is the
/// number 2 for an `Int!` field and the string `"2"` for a `String!` one, and
/// only the schema knows which was meant.
fn query_kind(api: &Api, f: &Field) -> &'static str {
    match api.find_type(f.ty.base_name()) {
        // An enum value is a string on the wire, whatever it is called in Rust.
        Some(ApiType::Enum(_)) => "Str",
        Some(ApiType::Scalar(s)) => match s.openapi_type.as_str() {
            "integer" => "Int",
            "number" => "Float",
            "boolean" => "Bool",
            "string" => "Str",
            // The unconstrained `JSON` scalar declares no OpenAPI type at all.
            _ => "Json",
        },
        // An object has no query-string spelling of its own, so it travels as
        // JSON text — which is what the TypeScript client writes for one.
        _ => "Json",
    }
}

fn rust_type(api: &Api, ty: &TypeRef) -> String {
    let inner = rust_type_non_null(api, ty);
    if ty.is_nullable() {
        format!("Option<{inner}>")
    } else {
        inner
    }
}

fn rust_type_non_null(api: &Api, ty: &TypeRef) -> String {
    match ty {
        TypeRef::Named { name, .. } => scalar_rust_name(api, name),
        TypeRef::List { inner, .. } => format!("Vec<{}>", rust_type(api, inner)),
    }
}

/// Field type inside `owner`, inserting `Box` where the reference would make
/// the struct infinitely sized.
fn field_rust_type(api: &Api, owner: &str, ty: &TypeRef) -> String {
    let needs_box = matches!(ty, TypeRef::Named { name, .. }
        if name == owner || api.reaches(name, owner));

    if !needs_box {
        return rust_type(api, ty);
    }
    let inner = rust_type_non_null(api, ty);
    if ty.is_nullable() {
        format!("Option<Box<{inner}>>")
    } else {
        format!("Box<{inner}>")
    }
}

fn scalar_rust_name(api: &Api, name: &str) -> String {
    match api.find_scalar(name) {
        // A newtype scalar is referred to by its own name; the inner
        // representation only appears in the wrapper's definition.
        Some(s) if s.rust_newtype => s.name.clone(),
        Some(s) => s.rust.clone(),
        None => name.to_string(),
    }
}
