//! TypeScript emitter: interfaces, unions, a fetch-based RPC client and
//! TanStack Query helpers. Reads only the IR.

use std::fmt::Write;

use crate::ir::*;

const HEADER: &str = "// @generated by graphql-rpcgen. Source of truth: api/**/*.graphql
// DO NOT EDIT MANUALLY.
";

pub fn generate(api: &Api) -> String {
    let mut out = String::new();
    out.push_str(HEADER);

    emit_types(&mut out, api);
    emit_error_types(&mut out, api);
    emit_client(&mut out);
    emit_services(&mut out, api);
    emit_api_object(&mut out, api);

    out
}

/// A TypeScript string literal holding `value`.
///
/// Single-quoted to match the rest of the emitted file, with the characters
/// that would end the literal early escaped. Wire vocabularies are not chosen
/// by this compiler — `@variant(tag:)` takes whatever the other end calls a
/// thing, apostrophe included — so the quoting has to survive one.
///
/// `generate_zod` spells the same thing for the same reason; the two must agree
/// on the literal a tag produces.
fn quoted(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r");
    format!("'{escaped}'")
}

fn emit_doc(out: &mut String, indent: &str, description: &Option<String>) {
    let Some(text) = description else { return };
    if text.lines().count() == 1 {
        let _ = writeln!(out, "{indent}/** {text} */");
        return;
    }
    let _ = writeln!(out, "{indent}/**");
    for line in text.lines() {
        let _ = writeln!(out, "{indent} * {line}");
    }
    let _ = writeln!(out, "{indent} */");
}

fn emit_types(out: &mut String, api: &Api) {
    for ty in &api.types {
        match ty {
            ApiType::Scalar(_) => {}
            ApiType::Enum(e) => {
                out.push('\n');
                emit_doc(out, "", &e.description);
                // A union of literals stays structural, so plain strings from
                // the server assign without a runtime enum object.
                let variants = e
                    .values
                    .iter()
                    .map(|v| quoted(v.wire_name()))
                    .collect::<Vec<_>>()
                    .join(" | ");
                let _ = writeln!(out, "export type {} = {variants}", e.name);
            }
            ApiType::Object(o) => {
                out.push('\n');
                emit_doc(out, "", &o.description);
                let _ = writeln!(out, "export interface {} {{", o.name);
                for f in &o.fields {
                    emit_interface_field(out, api, f);
                }
                out.push_str("}\n");
            }
            ApiType::InputObject(i) if i.one_of => emit_one_of(out, api, i),
            ApiType::InputObject(i) => {
                out.push('\n');
                emit_doc(out, "", &i.description);
                let _ = writeln!(out, "export interface {} {{", i.name);
                for f in &i.fields {
                    emit_interface_field(out, api, f);
                }
                out.push_str("}\n");
            }
            ApiType::Union(u) => {
                out.push('\n');
                emit_doc(out, "", &u.description);
                let arms = u
                    .members
                    .iter()
                    .map(|m| {
                        format!(
                            "  | ({{ {}: {} }} & {})",
                            u.discriminator,
                            quoted(&m.tag),
                            m.name
                        )
                    })
                    .collect::<Vec<_>>()
                    .join("\n");
                let _ = writeln!(out, "export type {} =\n{arms}", u.name);
            }
        }
    }
}

fn emit_interface_field(out: &mut String, api: &Api, f: &Field) {
    emit_doc(out, "  ", &f.description);
    let optional = if f.ty.is_nullable() { "?" } else { "" };
    let _ = writeln!(out, "  {}{optional}: {}", f.name, ts_type(api, &f.ty));
}

/// `@oneOf` becomes an exclusive union: each arm marks the other keys `never`,
/// so supplying two variants is a type error rather than a runtime surprise.
fn emit_one_of(out: &mut String, api: &Api, i: &InputObjectType) {
    out.push('\n');
    emit_doc(out, "", &i.description);
    let _ = writeln!(out, "export type {} =", i.name);
    for (index, field) in i.fields.iter().enumerate() {
        let mut arm = String::from("  | {\n");
        for other in &i.fields {
            if other.name == field.name {
                let _ = writeln!(
                    arm,
                    "      {}: {}",
                    other.name,
                    ts_type_non_null(api, &other.ty)
                );
            } else {
                let _ = writeln!(arm, "      {}?: never", other.name);
            }
        }
        arm.push_str("    }");
        out.push_str(&arm);
        if index + 1 < i.fields.len() {
            out.push('\n');
        }
    }
    out.push('\n');
}

/// The wire error shape, mirroring `treat::ErrorMessage`.
///
/// There is no payload type per code: an error is a `code`, a `message` and
/// optional `meta`, so `RpcErrorCode` is simply the registry enum.
fn emit_error_types(out: &mut String, api: &Api) {
    let registry = crate::semantic::ERROR_CODE_ENUM;
    if !matches!(api.find_type(registry), Some(ApiType::Enum(_))) {
        return;
    }

    let _ = write!(
        out,
        "\n/** Every code this API can return, declared or emitted by the runtime. */\n\
         export type RpcErrorCode = {registry}\n"
    );

    // Emitted by the runtime rather than declared in SDL: a malformed body or
    // an unexpected server failure can occur on any operation.
    let runtime_codes = crate::semantic::RUNTIME_ERROR_CODES
        .iter()
        .map(|c| format!("'{c}'"))
        .collect::<Vec<_>>()
        .join(" | ");
    let _ = write!(
        out,
        "\n/** Transport-level codes the runtime can return for any operation. */\n\
         export type RpcRuntimeErrorCode = {runtime_codes}\n"
    );

    out.push_str("\n/** Locator for the offending input (JSON:API `source`). */\n");
    out.push_str("export interface RpcErrorSource {\n  /** RFC 6901 JSON Pointer, e.g. `/device_info/sdk_version`. */\n  pointer?: string\n  parameter?: string\n  header?: string\n}\n");

    out.push_str("\n/** One entry of the wire `errors[]` array. */\n");
    out.push_str("export interface RpcErrorItem {\n");
    out.push_str("  code: RpcErrorCode\n");
    out.push_str("  message?: string\n");
    // An object rather than `unknown`: `meta` is a bag of named details, so
    // indexing it must not require a cast at every call site.
    out.push_str(
        "  /** Free-form context; its keys depend on the code. */\n  \
         meta?: Record<string, unknown>\n",
    );
    out.push_str("  source?: RpcErrorSource\n");
    // RFC 9457 `type` and `instance`. The server can set either on any error, so
    // a client that does not declare them drops them silently.
    out.push_str(
        "  /** RFC 9457 `type`: a URI identifying the error kind. */\n  \
         type?: string\n",
    );
    out.push_str(
        "  /** RFC 9457 `instance`: id or URI of this specific occurrence. */\n  \
         instance?: string\n",
    );
    out.push_str("}\n");
}

fn emit_client(target: &mut String) {
    // The body is one raw literal, so the registry's value is substituted into
    // it afterwards rather than interpolated inline.
    let mut out = String::new();
    let out = &mut out;
    out.push_str(
        r#"
/**
 * The response envelope, used for both success and failure.
 *
 * A successful call carries `data`; a failed one carries `errors`. Each field
 * is omitted entirely when empty rather than sent as null.
 */
export interface RpcResponse<Output = unknown> {
  data?: Output
  meta?: Record<string, unknown>
  errors?: RpcErrorItem[]
}

/**
 * Thrown whenever a response carries `errors[]`.
 *
 * The status line is not the signal: this API answers `200 OK` even when the
 * call failed, so `errors[]` decides the outcome.
 */
export class RpcError extends Error {
  readonly status: number
  readonly errors: RpcErrorItem[]

  constructor(status: number, errors: RpcErrorItem[]) {
    super(errors[0]?.message ?? `RPC request failed with status ${status}`)
    this.name = 'RpcError'
    this.status = status
    this.errors = errors
  }

  /** Whether any entry carries `code`. */
  is(code: RpcErrorCode): boolean {
    return this.errors.some((e) => e.code === code)
  }

  /** First `meta` payload matching `code`, if present. */
  metaFor(code: RpcErrorCode): Record<string, unknown> | undefined {
    return this.errors.find((e) => e.code === code)?.meta
  }

  /**
   * JSON Pointer to the field that caused the failure, when the server
   * located one — set for `invalid_body` rejections.
   */
  get pointer(): string | undefined {
    return this.errors.find((e) => e.source?.pointer)?.source?.pointer
  }
}

export interface RpcClientOptions {
  baseUrl?: string
  /** Extra headers merged into every request. */
  headers?: Record<string, string>
  fetch?: typeof globalThis.fetch
  /**
   * Called with every request before it is sent, and expected to throw when the
   * input breaks a constraint the SDL declares.
   *
   * The generated zod target exports a `validateInput` with exactly this shape,
   * so wiring it is `new RpcClient({ validate: validateInput })`. It is a hook
   * rather than a built-in import so a client that does not want a validation
   * library in its bundle still has no dependencies. The server checks the same
   * rules regardless — this only moves the rejection off the network.
   */
  validate?: (path: string, input: unknown) => void
}

export interface RpcCallOptions {
  signal?: AbortSignal
  /**
   * `Content-Type` for a raw request body, overriding the operation's first
   * declared media type.
   *
   * An operation accepting several is asking the caller to pick: an import
   * taking JSON or CSV cannot be sent as both, and only the caller knows which
   * file it holds.
   */
  contentType?: string
}

/** Minimal typed wrapper over fetch. Every operation is POST + JSON. */
export class RpcClient {
  private readonly baseUrl: string
  private readonly headers: Record<string, string>
  private readonly fetchImpl: typeof globalThis.fetch
  private readonly validate?: (path: string, input: unknown) => void

  constructor(options: RpcClientOptions = {}) {
    // Paths from the IR are absolute (/rpc/...), so the base URL only
    // contributes an origin or prefix.
    this.baseUrl = (options.baseUrl ?? '').replace(/\/$/, '')
    this.headers = options.headers ?? {}
    this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis)
    this.validate = options.validate
  }

  async call<Output>(path: string, input: unknown, options: RpcCallOptions = {}): Promise<Output> {
    // Throws before the request is built, so an input the server would reject
    // costs no round trip.
    this.validate?.(path, input)

    const response = await this.fetchImpl(`${this.baseUrl}${path}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...this.headers },
      body: JSON.stringify(input),
      signal: options.signal,
    })

    let body: RpcResponse<Output> | undefined
    try {
      body = (await response.json()) as RpcResponse<Output>
    } catch {
      // Non-JSON body; handled below.
    }

    // `errors[]` decides the outcome, not the status line, which is always 200
    // here. The `x-rpc-status` header carries the same signal out of band.
    if (body?.errors?.length) {
      throw new RpcError(response.status, body.errors)
    }
    if (!response.ok || body === undefined) {
      throw new RpcError(response.status, [syntheticError(response.status)])
    }
    return body.data as Output
  }

  /**
   * An operation whose request or response body is not the JSON envelope.
   *
   * Returns the `Response` rather than a parsed value: a raw body is bytes, and
   * the headers that come with it — `Content-Disposition`, `Content-Type` — are
   * part of the answer for a download.
   *
   * A failure still arrives as the JSON envelope, so a JSON content type on an
   * operation that never answers JSON is read as one and thrown.
   */
  async raw(
    path: string,
    input: object | undefined,
    spec: RpcRawSpec,
    options: RpcCallOptions = {},
  ): Promise<Response> {
    this.validate?.(path, input ?? {})

    // Generated input types are interfaces, which have no index signature, so
    // the widening happens here rather than at every call site.
    const fields = input as Record<string, unknown> | undefined
    const { body, params } = splitRawInput(fields, spec.bodyField)
    // With the one body taken by the payload, the parameters have nowhere left
    // to go but the URL.
    const url = spec.bodyField
      ? `${this.baseUrl}${path}${toQuery(params)}`
      : `${this.baseUrl}${path}`

    const headers: Record<string, string> = { ...this.headers }
    const requestType = options.contentType ?? spec.requestType
    if (requestType) headers['Content-Type'] = requestType
    else if (!spec.bodyField) headers['Content-Type'] = 'application/json'

    const response = await this.fetchImpl(url, {
      method: 'POST',
      headers,
      body: spec.bodyField ? (body as BodyInit) : JSON.stringify(input ?? {}),
      signal: options.signal,
    })

    const isJson = response.headers.get('content-type')?.includes('application/json') ?? false
    if (!response.ok || (spec.rawResponse && isJson)) {
      const envelope = (await response.json().catch(() => undefined)) as
        | RpcResponse<unknown>
        | undefined
      throw new RpcError(
        response.status,
        envelope?.errors?.length ? envelope.errors : [syntheticError(response.status)],
      )
    }
    return response
  }

  /** A raw request with an ordinary JSON answer — an upload reporting a result. */
  async rawJson<Output>(
    path: string,
    input: object | undefined,
    spec: RpcRawSpec,
    options: RpcCallOptions = {},
  ): Promise<Output> {
    const response = await this.raw(path, input, spec, options)
    const body = (await response.json().catch(() => undefined)) as RpcResponse<Output> | undefined
    if (body?.errors?.length) throw new RpcError(response.status, body.errors)
    if (body === undefined) throw new RpcError(response.status, [syntheticError(response.status)])
    return body.data as Output
  }

  /**
   * Open a subscription over Server-Sent Events.
   *
   * `EventSource` can only GET, so the input travels in the query string. Each
   * `data:` frame is one JSON event of the declared type; the connection is
   * closed by calling `close()` on what this returns.
   */
  subscribe<Event>(
    path: string,
    input: object | undefined,
    handlers: RpcEventHandlers<Event>,
  ): RpcSubscription {
    this.validate?.(path, input ?? {})

    const query = toQuery(input as Record<string, unknown> | undefined)
    const source = new EventSource(`${this.baseUrl}${path}${query}`)
    source.onmessage = (message) => {
      // A frame that is not the declared event is a server bug, and swallowing
      // it would present a stalled stream as a quiet one.
      handlers.onEvent(JSON.parse(message.data) as Event)
    }
    if (handlers.onOpen) source.onopen = () => handlers.onOpen?.()
    // `EventSource` reconnects on its own; the handler is for reporting, not
    // for retrying.
    if (handlers.onError) source.onerror = (event) => handlers.onError?.(event)
    return { close: () => source.close() }
  }
}

/** How an operation's non-JSON bodies are carried. */
export interface RpcRawSpec {
  /** Input field holding the request body; the rest become query parameters. */
  bodyField?: string
  /** `Content-Type` for that body. */
  requestType?: string
  /** Whether the response body is opaque, so a JSON answer means failure. */
  rawResponse?: boolean
}

export interface RpcEventHandlers<Event> {
  onEvent: (event: Event) => void
  onOpen?: () => void
  onError?: (event: globalThis.Event) => void
}

export interface RpcSubscription {
  close(): void
}

/** Split an input into the field carrying the body and everything else. */
function splitRawInput(
  input: Record<string, unknown> | undefined,
  bodyField: string | undefined,
): { body: unknown; params: Record<string, unknown> | undefined } {
  if (!input || !bodyField) return { body: undefined, params: input }
  const { [bodyField]: body, ...params } = input
  return { body, params }
}

/**
 * An input object as a query string.
 *
 * Absent values are omitted rather than sent empty, so an optional parameter
 * left out reaches the server as absent and takes its default. Arrays repeat
 * the key, which is what a server reading `getAll` expects.
 */
function toQuery(input: Record<string, unknown> | undefined): string {
  if (!input) return ''
  const params = new URLSearchParams()
  for (const [key, value] of Object.entries(input)) {
    if (value === undefined || value === null) continue
    if (Array.isArray(value)) {
      for (const item of value) params.append(key, String(item))
    } else if (typeof value === 'object') {
      params.append(key, JSON.stringify(value))
    } else {
      params.append(key, String(value))
    }
  }
  const query = params.toString()
  return query ? `?${query}` : ''
}

/** Stands in when a failure carries no usable envelope. */
function syntheticError(status: number): RpcErrorItem {
  return {
    code: 'INTERNAL_ERROR_PLACEHOLDER',
    message: `RPC request failed with status ${status}`,
  } as RpcErrorItem
}
"#,
    );

    target.push_str(&out.replace(
        "INTERNAL_ERROR_PLACEHOLDER",
        crate::semantic::CODE_INTERNAL_ERROR,
    ));
}

/// Per-service call methods, grouped into one object per service.
fn emit_services(out: &mut String, api: &Api) {
    for service in &api.services {
        out.push('\n');
        emit_doc(out, "", &service.description);
        let _ = writeln!(
            out,
            "export function create{}Operations(client: RpcClient) {{\n  return {{",
            service.name
        );
        for op in &service.operations {
            emit_doc(out, "    ", &op.description);
            let _ = writeln!(out, "    {}: {},", op.name, call_expr(api, op, "      "));
        }
        out.push_str("  }\n}\n");
        let _ = writeln!(
            out,
            "\nexport type {}Operations = ReturnType<typeof create{}Operations>",
            service.name, service.name
        );
    }
}

/// The `api` factory: TanStack helpers layered over the call methods.
fn emit_api_object(out: &mut String, api: &Api) {
    out.push_str(
        r#"
/** Deterministic TanStack query key: [service, operation, input]. */
export function queryKey(service: string, operation: string, input: unknown) {
  return [service, operation, input] as const
}

export interface QueryOptionsResult<Output> {
  queryKey: readonly unknown[]
  queryFn: (context: { signal?: AbortSignal }) => Promise<Output>
}

export interface MutationOptionsResult<Input, Output> {
  mutationKey: readonly unknown[]
  mutationFn: (input: Input) => Promise<Output>
}
"#,
    );

    out.push_str("\n/** Typed facade over the RPC client, including TanStack helpers. */\n");
    out.push_str("export function createApi(client: RpcClient) {\n  return {\n");

    for service in &api.services {
        let service_key = service.name.to_lowercase();
        let _ = writeln!(out, "    {service_key}: {{");
        for op in &service.operations {
            let input = ts_input_type(api, op);
            let output = ts_type(api, &op.output);
            // With no input there is no parameter to declare and nothing to
            // send but `{}`; the helpers keep their arity via `void`.
            let param = ts_input_param(api, op);
            let body = if op.input.is_some() { "input" } else { "{}" };
            let key_param = param.clone();
            let key_arg = if op.input.is_some() {
                "input"
            } else {
                "undefined"
            };
            let _ = writeln!(out, "      {}: {{", op.name);
            let verb = if op.kind == OperationKind::Subscription {
                "subscribe"
            } else {
                "call"
            };
            let _ = writeln!(out, "        {verb}: {},", call_expr(api, op, "          "));
            let _ = writeln!(
                out,
                "        queryKey: ({key_param}) => queryKey('{service_key}', '{}', {key_arg}),",
                op.name
            );

            // A raw response is a single-use stream: caching it would hand the
            // second reader a consumed body, so a download gets no TanStack
            // helper and stays an explicit call.
            if op.raw_response.is_some() {
                out.push_str("      },\n");
                continue;
            }

            let call = match raw_spec(api, op) {
                Some(spec) => format!("client.rawJson<{output}>('{}', {body}, {spec}", op.path),
                None => format!("client.call<{output}>('{}', {body}", op.path),
            };

            match op.kind {
                OperationKind::Query => {
                    let _ = writeln!(
                        out,
                        "        queryOptions: ({key_param}): QueryOptionsResult<{output}> => ({{\n          queryKey: queryKey('{service_key}', '{}', {key_arg}),\n          queryFn: ({{ signal }}) => {call}, {{ signal }}),\n        }}),",
                        op.name
                    );
                }
                OperationKind::Mutation => {
                    let _ = writeln!(
                        out,
                        "        mutationOptions: (): MutationOptionsResult<{input}, {output}> => ({{\n          mutationKey: ['{service_key}', '{}'],\n          mutationFn: ({key_param}) => {call}),\n        }}),",
                        op.name
                    );
                }
                // A stream has no single value to cache, so there are no
                // TanStack options for it — `queryKey` is still emitted above
                // so an event can be pushed into the cache of a related query.
                OperationKind::Subscription => {}
            }
            out.push_str("      },\n");
        }
        out.push_str("    },\n");
    }

    out.push_str("  }\n}\n");
    out.push_str("\nexport type Api = ReturnType<typeof createApi>\n");
}

/// The lambda that performs one operation, whatever its transport.
///
/// Shared by the plain per-service object and by the TanStack facade so the two
/// cannot describe the same call differently.
fn call_expr(api: &Api, op: &Operation, indent: &str) -> String {
    let output = ts_type(api, &op.output);
    let param = ts_input_param(api, op);
    let leading = if param.is_empty() {
        String::new()
    } else {
        format!("{param}, ")
    };
    let body = if op.input.is_some() { "input" } else { "{}" };

    if op.kind == OperationKind::Subscription {
        return format!(
            "({leading}handlers: RpcEventHandlers<{output}>): RpcSubscription =>\n{indent}\
             client.subscribe<{output}>('{}', {body}, handlers)",
            op.path
        );
    }

    let Some(spec) = raw_spec(api, op) else {
        return format!(
            "({leading}options?: RpcCallOptions): Promise<{output}> =>\n{indent}\
             client.call<{output}>('{}', {body}, options)",
            op.path
        );
    };

    // A raw response is bytes plus the headers that describe them, so the
    // caller gets the `Response` and reads whichever it needs.
    if op.raw_response.is_some() {
        format!(
            "({leading}options?: RpcCallOptions): Promise<Response> =>\n{indent}\
             client.raw('{}', {body}, {spec}, options)",
            op.path
        )
    } else {
        format!(
            "({leading}options?: RpcCallOptions): Promise<{output}> =>\n{indent}\
             client.rawJson<{output}>('{}', {body}, {spec}, options)",
            op.path
        )
    }
}

/// The `RpcRawSpec` literal for an operation, or `None` when it is plain JSON.
fn raw_spec(api: &Api, op: &Operation) -> Option<String> {
    if op.raw_request.is_none() && op.raw_response.is_none() {
        return None;
    }
    let mut parts = Vec::new();
    if let Some(field) = api.body_field(op) {
        parts.push(format!("bodyField: {}", quoted(&field.name)));
    }
    // The first declared media type is what a generated caller sends; an
    // operation accepting several is describing what it will take, not asking
    // the client to choose.
    if let Some(types) = &op.raw_request {
        if let Some(first) = types.first() {
            parts.push(format!("requestType: {}", quoted(first)));
        }
    }
    if op.raw_response.is_some() {
        parts.push("rawResponse: true".to_string());
    }
    Some(format!("{{ {} }}", parts.join(", ")))
}

/// The type of an operation's `input`, or `void` when it declares none.
///
/// `void` keeps every helper's shape: `queryKey(.., input)` and `mutationFn`
/// still take one parameter, so the TanStack signatures are unchanged and a
/// caller simply passes nothing.
fn ts_input_type(api: &Api, op: &Operation) -> String {
    match &op.input {
        Some(input) => ts_type(api, input),
        None => "void".to_string(),
    }
}

/// The parameter declaration for an operation's input, empty when it has none.
fn ts_input_param(api: &Api, op: &Operation) -> String {
    match &op.input {
        Some(input) => format!("input: {}", ts_type(api, input)),
        None => String::new(),
    }
}

fn ts_type(api: &Api, ty: &TypeRef) -> String {
    let inner = ts_type_non_null(api, ty);
    if ty.is_nullable() {
        format!("{inner} | null")
    } else {
        inner
    }
}

fn ts_type_non_null(api: &Api, ty: &TypeRef) -> String {
    match ty {
        TypeRef::Named { name, .. } => scalar_ts_name(api, name),
        TypeRef::List { inner, .. } => {
            let item = ts_type(api, inner);
            // Parenthesise unions so `(string | null)[]` is not read as
            // `string | (null[])`.
            if item.contains('|') {
                format!("({item})[]")
            } else {
                format!("{item}[]")
            }
        }
    }
}

fn scalar_ts_name(api: &Api, name: &str) -> String {
    match api.find_scalar(name) {
        Some(s) => s.typescript.clone(),
        None => name.to_string(),
    }
}
