//! Rust client emitter: a typed method per operation over an HTTP transport.
//!
//! The client is a separate target from the server because its dependencies
//! are: it needs an HTTP client, not a web framework. A project consuming an
//! API it does not serve generates `rust_types` + `rust_client` and compiles
//! neither `axum` nor `treat`'s server half.
//!
//! Operations are grouped by service, matching the TypeScript client, so
//! `client.clans().create(..)` reads the same in both languages.
//!
//! The wire contract is the one the server emits: always `200 OK`, with the
//! outcome in `errors[]`. That check lives in the preamble template, so a
//! project on another HTTP stack replaces the template rather than the
//! emitter.

use std::fmt::Write;

use crate::config::Config;
use crate::error::CompileError;
use crate::ir::*;
use crate::naming::{codes_type_name, pascal_case, snake_case};
use crate::template::{Template, Vars};

const HEADER: &str = "// @generated by graphql-rpcgen. Source of truth: api/**/*.graphql
// DO NOT EDIT MANUALLY.
";

const DEFAULT_PREAMBLE: &str = include_str!("../templates/rust/client_preamble.mustache");
const DEFAULT_METHOD: &str = include_str!("../templates/rust/client_method.mustache");
/// An operation with no `input` argument still sends `{}`, so the wire format
/// is unchanged; only the method signature loses its parameter.
const DEFAULT_METHOD_NO_INPUT: &str =
    include_str!("../templates/rust/client_method_no_input.mustache");
/// Streaming and raw-body support, emitted only for an API that has an
/// operation needing it so a plain JSON client compiles none of it.
const DEFAULT_RUNTIME: &str = include_str!("../templates/rust/client_runtime.mustache");
/// One method form per shape a call can take, for the same reason the server
/// has one handler form per shape: a flat mustache context cannot branch.
const DEFAULT_METHOD_SUBSCRIPTION: &str =
    include_str!("../templates/rust/client_method_subscription.mustache");
const DEFAULT_METHOD_SUBSCRIPTION_NO_INPUT: &str =
    include_str!("../templates/rust/client_method_subscription_no_input.mustache");
const DEFAULT_METHOD_RAW_RESPONSE: &str =
    include_str!("../templates/rust/client_method_raw_response.mustache");
const DEFAULT_METHOD_RAW_RESPONSE_NO_INPUT: &str =
    include_str!("../templates/rust/client_method_raw_response_no_input.mustache");
const DEFAULT_METHOD_RAW_REQUEST: &str =
    include_str!("../templates/rust/client_method_raw_request.mustache");
const DEFAULT_METHOD_RAW_BOTH: &str =
    include_str!("../templates/rust/client_method_raw_both.mustache");

/// Default name of the generated client struct.
const DEFAULT_CLIENT_NAME: &str = "ApiClient";

/// Variables the client preamble may reference, besides `template_vars`.
const PREAMBLE_VARS: [&str; 3] = ["error_code_enum", "types_import", "client_name"];
/// Variables the method template may reference, besides `template_vars`.
///
/// `error` names the operation's own code enum, which is what the call fails
/// with — the flat registry would let a caller match on codes this operation
/// never returns.
const METHOD_VARS: [&str; 7] = [
    "method",
    "input",
    "output",
    "path",
    "operation_id",
    "error",
    // The input field a raw request sends as its body; empty for every other
    // form, which never mentions it.
    "body_field",
];

pub fn generate(api: &Api, config: &Config) -> Result<String, CompileError> {
    let client = &config.rust_client;
    let extra_names: Vec<&str> = client.template_vars.keys().map(String::as_str).collect();

    let compile = |source: &str,
                   origin: &str,
                   path: &Option<std::path::PathBuf>,
                   base: &[&str]|
     -> Result<Template, CompileError> {
        let mut allowed: Vec<&str> = base.to_vec();
        allowed.extend_from_slice(&extra_names);
        match path {
            Some(path) => Template::from_file(path, &allowed),
            None => Template::compile(source, origin, &allowed),
        }
    };

    let preamble = compile(
        DEFAULT_PREAMBLE,
        "<builtin client preamble>",
        &client.preamble_template,
        &PREAMBLE_VARS,
    )?;
    let method = compile(
        DEFAULT_METHOD,
        "<builtin client method>",
        &client.method_template,
        &METHOD_VARS,
    )?;
    let method_no_input = compile(
        DEFAULT_METHOD_NO_INPUT,
        "<builtin no-input client method>",
        &client.method_no_input_template,
        &METHOD_VARS,
    )?;
    // The streaming and raw forms have no config hook: they are the built-ins
    // or nothing, until a project asks to replace one.
    let runtime = compile(
        DEFAULT_RUNTIME,
        "<builtin client runtime>",
        &None,
        &PREAMBLE_VARS,
    )?;
    let methods = RawMethods {
        subscription: compile(
            DEFAULT_METHOD_SUBSCRIPTION,
            "<builtin subscription client method>",
            &None,
            &METHOD_VARS,
        )?,
        subscription_no_input: compile(
            DEFAULT_METHOD_SUBSCRIPTION_NO_INPUT,
            "<builtin no-input subscription client method>",
            &None,
            &METHOD_VARS,
        )?,
        raw_response: compile(
            DEFAULT_METHOD_RAW_RESPONSE,
            "<builtin raw-response client method>",
            &None,
            &METHOD_VARS,
        )?,
        raw_response_no_input: compile(
            DEFAULT_METHOD_RAW_RESPONSE_NO_INPUT,
            "<builtin no-input raw-response client method>",
            &None,
            &METHOD_VARS,
        )?,
        raw_request: compile(
            DEFAULT_METHOD_RAW_REQUEST,
            "<builtin raw-request client method>",
            &None,
            &METHOD_VARS,
        )?,
        raw_both: compile(
            DEFAULT_METHOD_RAW_BOTH,
            "<builtin raw client method>",
            &None,
            &METHOD_VARS,
        )?,
    };

    let vars = |pairs: &[(&str, &str)]| -> Vars {
        let mut vars = client.template_vars.clone();
        for (key, value) in pairs {
            vars.insert((*key).to_string(), (*value).to_string());
        }
        vars
    };

    let types_import = match client.resolved_types_path(&config.rust) {
        Some(path) => format!("\nuse {path}::*;\n"),
        None => String::new(),
    };

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(&preamble.render(&vars(&[
        ("error_code_enum", crate::semantic::ERROR_CODE_ENUM),
        ("types_import", &types_import),
        ("client_name", DEFAULT_CLIENT_NAME),
    ]))?);

    if api
        .services
        .iter()
        .flat_map(|service| &service.operations)
        .any(needs_runtime)
    {
        out.push_str(&runtime.render(&vars(&[
            ("error_code_enum", crate::semantic::ERROR_CODE_ENUM),
            ("types_import", ""),
            ("client_name", DEFAULT_CLIENT_NAME),
        ]))?);
    }

    for service in &api.services {
        emit_service(
            &mut out,
            api,
            service,
            &method,
            &method_no_input,
            &methods,
            &vars,
        )?;
    }

    Ok(out)
}

/// The method forms for operations that are not JSON in and JSON out.
struct RawMethods {
    subscription: Template,
    subscription_no_input: Template,
    raw_response: Template,
    raw_response_no_input: Template,
    raw_request: Template,
    /// Bytes in and bytes out: an operation declaring both `@raw` directions.
    raw_both: Template,
}

/// Whether an operation needs the streaming and raw-body runtime.
fn needs_runtime(op: &Operation) -> bool {
    op.kind == OperationKind::Subscription || op.raw_request.is_some() || op.raw_response.is_some()
}

/// One service: an accessor on the client plus a borrowed group holding the
/// operations.
///
/// The group borrows the client rather than cloning it, so
/// `client.clans().create(..)` costs nothing beyond the call itself.
fn emit_service(
    out: &mut String,
    api: &Api,
    service: &Service,
    method: &Template,
    method_no_input: &Template,
    methods: &RawMethods,
    vars: &impl Fn(&[(&str, &str)]) -> Vars,
) -> Result<(), CompileError> {
    let group = format!("{}Operations", pascal_case(&service.name));
    let accessor = snake_case(&service.name);

    out.push('\n');
    emit_doc(out, "", &service.description);
    let _ = writeln!(out, "pub struct {group}<'a> {{");
    let _ = writeln!(out, "    client: &'a {DEFAULT_CLIENT_NAME},");
    out.push_str("}\n\n");

    let _ = writeln!(out, "impl {DEFAULT_CLIENT_NAME} {{");
    // The description belongs to the group type, which is where the operations
    // are; repeating it on the accessor would say the same thing twice on the
    // same screen.
    let _ = writeln!(out, "    /// The `{}` operations.", service.name);
    let _ = writeln!(out, "    pub fn {accessor}(&self) -> {group}<'_> {{");
    let _ = writeln!(out, "        {group} {{ client: self }}");
    out.push_str("    }\n}\n\n");

    let _ = writeln!(out, "impl {group}<'_> {{");
    for (index, op) in service.operations.iter().enumerate() {
        if index > 0 {
            out.push('\n');
        }
        emit_doc(out, "    ", &op.description);
        emit_media_types_doc(out, op);
        emit_errors_doc(out, op);
        let template = method_template(method, method_no_input, methods, op);
        let input = match &op.input {
            Some(input) => rust_type(api, input),
            None => String::new(),
        };
        let body_field = match api.body_field(op) {
            Some(f) => snake_case(&f.name),
            None => String::new(),
        };
        out.push_str(&template.render(&vars(&[
            ("method", &snake_case(&op.name)),
            ("input", &input),
            ("output", &rust_type(api, &op.output)),
            ("path", &op.path),
            ("operation_id", &op.operation_id),
            ("error", &codes_type_name(&service.name, &op.name)),
            ("body_field", &body_field),
        ]))?);
    }
    out.push_str("}\n");

    Ok(())
}

fn emit_doc(out: &mut String, indent: &str, description: &Option<String>) {
    let Some(text) = description else { return };
    for line in text.lines() {
        let _ = writeln!(out, "{indent}/// {line}");
    }
}

/// The method form for one operation: what it sends, and what it answers with.
fn method_template<'a>(
    method: &'a Template,
    method_no_input: &'a Template,
    methods: &'a RawMethods,
    op: &Operation,
) -> &'a Template {
    let has_input = op.input.is_some();
    match (
        op.kind,
        has_input,
        op.raw_request.is_some(),
        op.raw_response.is_some(),
    ) {
        (OperationKind::Subscription, true, _, _) => &methods.subscription,
        (OperationKind::Subscription, false, _, _) => &methods.subscription_no_input,
        // A raw request always has an input: its payload is a field of one.
        (_, _, true, true) => &methods.raw_both,
        (_, _, true, false) => &methods.raw_request,
        (_, true, false, true) => &methods.raw_response,
        (_, false, false, true) => &methods.raw_response_no_input,
        (_, true, false, false) => method,
        (_, false, false, false) => method_no_input,
    }
}

/// What a `@raw` operation accepts or answers with.
///
/// A raw request takes the content type as an argument, so the list the SDL
/// declares is what the caller picks from; a raw response states what may
/// arrive, since the caller reads the bytes itself.
fn emit_media_types_doc(out: &mut String, op: &Operation) {
    let (label, types) = match (&op.raw_request, &op.raw_response) {
        (Some(types), _) => ("Accepts", types),
        (None, Some(types)) => ("Answers with", types),
        (None, None) => return,
    };
    if op.description.is_some() {
        out.push_str("    ///\n");
    }
    let _ = writeln!(out, "    /// {label}: `{}`.", types.join("`, `"));
}

/// The codes an operation declares with `@throws`, so a caller can see what to
/// branch on without opening the SDL.
fn emit_errors_doc(out: &mut String, op: &Operation) {
    if op.errors.is_empty() {
        return;
    }
    if op.description.is_some() {
        out.push_str("    ///\n");
    }
    // The heading is the rustdoc convention; what it introduces is this
    // operation's codes, so nothing else is said before the list.
    out.push_str("    /// # Errors\n    ///\n");
    for code in &op.errors {
        let _ = writeln!(out, "    /// - `{code}`");
    }
}

fn rust_type(api: &Api, ty: &TypeRef) -> String {
    let inner = rust_type_non_null(api, ty);
    if ty.is_nullable() {
        format!("Option<{inner}>")
    } else {
        inner
    }
}

fn rust_type_non_null(api: &Api, ty: &TypeRef) -> String {
    match ty {
        TypeRef::Named { name, .. } => match api.find_scalar(name) {
            Some(s) if s.rust_newtype => s.name.clone(),
            Some(s) => s.rust.clone(),
            None => name.to_string(),
        },
        TypeRef::List { inner, .. } => format!("Vec<{}>", rust_type(api, inner)),
    }
}
