//! The `graphql-rpcgen` version a project declares it was written against.
//!
//! Generated code is a contract between an SDL and one generator: a template
//! variable that disappears, a changed wire shape, a new required directive
//! argument all turn "the artifacts are stale" into "the artifacts are wrong".
//! A project therefore states which generator it expects, and a mismatch stops
//! the run rather than emitting code the project has never seen.
//!
//! The rule is Cargo's caret semantics for a `major.minor.patch` requirement:
//! the major must be equal, and the rest must be at least what was asked for.
//! A different major is a refusal in both directions — a newer generator may
//! have dropped what the project relies on, and an older one cannot know what
//! the project was written against.

use std::fmt;

use crate::error::CompileError;

/// This build's version, from the package manifest.
pub const CURRENT: &str = env!("CARGO_PKG_VERSION");

/// A `major.minor.patch` triple. No pre-release or build metadata: a generator
/// requirement is a floor, and comparing pre-release ordering would add rules
/// nobody writing an `rpcgen.toml` expects.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct Version {
    pub major: u64,
    pub minor: u64,
    pub patch: u64,
}

impl Version {
    /// Parse `major.minor.patch`. All three parts are required, so a bare
    /// `"1"` is an error rather than a silent `1.0.0` — the difference between
    /// those two is exactly what this check exists to catch.
    pub fn parse(text: &str) -> Result<Self, CompileError> {
        fn invalid(text: &str, why: &str) -> CompileError {
            CompileError::new(format!(
                "`{text}` is not a version: {why}. Expected `major.minor.patch`, e.g. `{CURRENT}`"
            ))
        }

        let mut parts = text.split('.');
        let mut next = |what: &str| -> Result<u64, CompileError> {
            let part = parts.next().ok_or_else(|| invalid(text, "too few parts"))?;
            if part.is_empty() {
                return Err(invalid(text, &format!("{what} is empty")));
            }
            part.parse::<u64>()
                .map_err(|_| invalid(text, &format!("{what} `{part}` is not a number")))
        };

        let major = next("major")?;
        let minor = next("minor")?;
        let patch = next("patch")?;
        if parts.next().is_some() {
            return Err(invalid(text, "too many parts"));
        }

        Ok(Self {
            major,
            minor,
            patch,
        })
    }

    /// Whether `self` satisfies `required` under caret semantics: same major,
    /// and not older within it.
    pub fn satisfies(self, required: Self) -> bool {
        self.major == required.major && self >= required
    }
}

impl fmt::Display for Version {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}.{}.{}", self.major, self.minor, self.patch)
    }
}

/// Compare this build against what a project requires, naming the reason.
///
/// `required` is the raw string from the config, so a malformed value is
/// reported as such rather than as a mismatch.
pub fn check(required: &str) -> Result<(), CompileError> {
    let required = Version::parse(required)?;
    // The running build's own version is generated by cargo, so a parse failure
    // here is a broken release rather than a user error — reported as such, with
    // the version test below pinning that it cannot happen in a real one.
    let current = Version::parse(CURRENT).map_err(|e| {
        CompileError::new(format!(
            "this build's own version `{CURRENT}` does not parse: {e}"
        ))
    })?;

    if current.satisfies(required) {
        return Ok(());
    }

    let why = if current.major != required.major {
        format!(
            "major version {} does not match the required {}; \
             generated code is not portable across majors",
            current.major, required.major
        )
    } else {
        "it is older than required".to_string()
    };

    Err(CompileError::new(format!(
        "graphql-rpcgen {current} cannot satisfy `rpcgen_version = \"{required}\"`: {why}. \
         Install a matching generator, or update the requirement if the project \
         has been checked against this one."
    )))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// What a test body answers with: the first failure ends it, carrying the
    /// message of whatever actually went wrong rather than a fixed one.
    type TestResult<T = ()> = Result<T, Box<dyn std::error::Error>>;

    /// The message of an error the test requires, or a failure naming what went
    /// through instead.
    fn refusal<T>(outcome: Result<T, CompileError>, what: &str) -> TestResult<String> {
        match outcome {
            Err(error) => Ok(error.to_string()),
            Ok(_) => Err(format!("{what} must be refused").into()),
        }
    }

    fn v(major: u64, minor: u64, patch: u64) -> Version {
        Version {
            major,
            minor,
            patch,
        }
    }

    #[test]
    fn a_triple_parses_into_its_parts() -> TestResult {
        assert_eq!(Version::parse("1.2.3")?, v(1, 2, 3));
        assert_eq!(Version::parse("0.0.0")?, v(0, 0, 0));
        // Not a semver range, so a large minor is just a number.
        assert_eq!(Version::parse("0.240.10")?, v(0, 240, 10));
        Ok(())
    }

    /// A bare major would otherwise read as `1.0.0`, which is a different
    /// requirement than the one the writer meant.
    #[test]
    fn a_partial_version_is_rejected() -> TestResult {
        for text in ["1", "1.2", "", "1.2.", ".2.3", "1..3"] {
            let err = refusal(Version::parse(text), text)?;
            assert!(err.contains("major.minor.patch"), "{text}: got {err}");
        }
        Ok(())
    }

    #[test]
    fn a_non_numeric_or_overlong_version_is_rejected() {
        for text in ["1.2.x", "1.2.3.4", "v1.2.3", "1.2.3-rc1"] {
            assert!(Version::parse(text).is_err(), "{text} must be rejected");
        }
    }

    #[test]
    fn the_same_version_satisfies_itself() {
        assert!(v(1, 2, 3).satisfies(v(1, 2, 3)));
    }

    #[test]
    fn a_newer_minor_or_patch_within_the_major_satisfies() {
        assert!(v(1, 3, 0).satisfies(v(1, 2, 3)));
        assert!(v(1, 2, 4).satisfies(v(1, 2, 3)));
    }

    #[test]
    fn an_older_version_within_the_major_does_not_satisfy() {
        assert!(!v(1, 2, 2).satisfies(v(1, 2, 3)));
        assert!(!v(1, 1, 9).satisfies(v(1, 2, 3)));
    }

    /// The clause that makes this more than a floor: a newer major is refused
    /// even though it is numerically greater.
    #[test]
    fn a_different_major_never_satisfies_in_either_direction() {
        assert!(!v(2, 0, 0).satisfies(v(1, 2, 3)));
        assert!(!v(0, 9, 9).satisfies(v(1, 2, 3)));
        assert!(!v(1, 0, 0).satisfies(v(2, 0, 0)));
    }

    /// 0.x majors are all zero, so under caret semantics 0.1 and 0.2 are the
    /// same major and only the floor applies. Worth pinning: it differs from
    /// Cargo's treatment of `^0.1`, and this is the range graphql-rpcgen itself
    /// is in.
    #[test]
    fn within_major_zero_only_the_floor_applies() {
        assert!(v(0, 2, 0).satisfies(v(0, 1, 0)));
        assert!(!v(0, 1, 0).satisfies(v(0, 2, 0)));
    }

    #[test]
    fn this_build_satisfies_its_own_version() -> TestResult {
        check(CURRENT)?;
        Ok(())
    }

    #[test]
    fn a_mismatched_major_names_the_reason() -> TestResult {
        let current = Version::parse(CURRENT)?;
        let other = format!("{}.0.0", current.major + 1);
        let err = refusal(check(&other), &other)?;
        assert!(err.contains("major version"), "got: {err}");
        assert!(err.contains(&other), "must quote the requirement: {err}");
        Ok(())
    }

    #[test]
    fn a_too_new_requirement_within_the_major_says_it_is_older() -> TestResult {
        let current = Version::parse(CURRENT)?;
        let newer = format!("{}.{}.0", current.major, current.minor + 1);
        let err = refusal(check(&newer), &newer)?;
        assert!(err.contains("older than required"), "got: {err}");
        Ok(())
    }

    #[test]
    fn a_malformed_requirement_is_reported_as_malformed_not_as_a_mismatch() -> TestResult {
        let err = refusal(check("nope"), "nope")?;
        assert!(err.contains("is not a version"), "got: {err}");
        Ok(())
    }
}
